
{
	"IdLearnSet":11,
	"Words":
	[
		{"English":"able", "Russian":"способный"},
		{"English":"bad", "Russian":"плохой"},
		{"English":"best", "Russian":"лучший"},
		{"English":"better", "Russian":"лучше"},
		{"English":"big", "Russian":"большой"},
		{"English":"black", "Russian":"черный"},
		{"English":"certain", "Russian":"определенный"},
		{"English":"clear", "Russian":"четкий"},
		{"English":"different", "Russian":"различный"},
		{"English":"early", "Russian":"ранний"},
		{"English":"easy", "Russian":"простой"},
		{"English":"economic", "Russian":"экономический"},
		{"English":"free", "Russian":"свободный"},
		{"English":"full", "Russian":"полный"},
		{"English":"good", "Russian":"хороший"},
		{"English":"great", "Russian":"отличный"},
		{"English":"hard", "Russian":"трудный"},
		{"English":"high", "Russian":"высокий"},
		{"English":"human", "Russian":"человеческий"},
		{"English":"important", "Russian":"важный"},
		{"English":"international", "Russian":"международный"},
		{"English":"large", "Russian":"большой"},
		{"English":"late", "Russian":"поздний"},
		{"English":"little", "Russian":"маленький"},
		{"English":"local", "Russian":"местный"},
		{"English":"long", "Russian":"длинный"},
		{"English":"low", "Russian":"низкий"},
		{"English":"major", "Russian":"главный"},
		{"English":"military", "Russian":"военный"},
		{"English":"national", "Russian":"национальный"},
		{"English":"new", "Russian":"новый"},
		{"English":"old", "Russian":"старый"},
		{"English":"only", "Russian":"только"},
		{"English":"other", "Russian":"другой"},
		{"English":"political", "Russian":"политический"},
		{"English":"possible", "Russian":"возможный"},
		{"English":"public", "Russian":"общественный"},
		{"English":"real", "Russian":"реальный"},
		{"English":"recent", "Russian":"недавний"},
		{"English":"small", "Russian":"маленький"},
		{"English":"social", "Russian":"общественный"},
		{"English":"special", "Russian":"особый"},
		{"English":"strong", "Russian":"сильный"},
		{"English":"sure", "Russian":"уверенный"},
		{"English":"true", "Russian":"истинный"},
		{"English":"white", "Russian":"белый"},
		{"English":"whole", "Russian":"целый"},
		{"English":"young", "Russian":"молодой"}
	]
}