
{
	"IdLearnSet":8,
	"Words":
	[
		{"Russian":"понедельник", "English":"Monday"},
		{"Russian":"вторник", "English":"Tuesday"},
		{"Russian":"среда", "English":"Wednesday"},
		{"Russian":"четверг", "English":"Thursday"},
		{"Russian":"пятница", "English":"Friday"},
		{"Russian":"суббота", "English":"Saturday"},
		{"Russian":"воскресенье", "English":"Sunday"},
		{"Russian":"будни", "English":"weekdays, working days"},
		{"Russian":"вечер", "English":"evening"},
		{"Russian":"вечером", "English":"in the evening"},
		{"Russian":"восход", "English":"sunrise"},
		{"Russian":"вчера", "English":"yesterday"},
		{"Russian":"выходной", "English":"day off"},
		{"Russian":"день", "English":"day"},
		{"Russian":"после полудня", "English":"afternoon"},
		{"Russian":"день рождения", "English":"birthday"},
		{"Russian":"днем", "English":"in the afternoon"},
		{"Russian":"завтра", "English":"tomorrow"},
		{"Russian":"закат", "English":"sunset"},
		{"Russian":"каждый день", "English":"every day"},
		{"Russian":"неделя", "English":"week"},
		{"Russian":"ночь", "English":"night"},
		{"Russian":"ночью", "English":"at night"},
		{"Russian":"в ночи in the night"},
		{"Russian":"позавчера", "English":"the day before yesterday"},
		{"Russian":"полдень", "English":"noon, midday"},
		{"Russian":"в полдень", "English":"at noon, at midday"},
		{"Russian":"полночь", "English":"midnight"},
		{"Russian":"в полночь", "English":"at midnight"},
		{"Russian":"послезавтра", "English":"the day after tomorrow"},
		{"Russian":"праздник", "English":"holiday"},
		{"Russian":"рассвет", "English":"dawn, daybreak, break of day"},
		{"Russian":"ни свет ни заря", "English":"at the crack of dawn"},
		{"Russian":"сегодня", "English":"today"},
		{"Russian":"семидневная неделя", "English":"the seven-day week"},
		{"Russian":"следующий день", "English":"next day"},
		{"Russian":"уикэнд, конец недели", "English":"weekend"},
		{"Russian":"утро", "English":"morning"},
		{"Russian":"утром", "English":"in the morning"},
		{"Russian":"хороший день", "English":"nice day"}
	]
}