
{
	"IdLearnSet":9,
	"Words":
	[
		{"English":"area", "Russian":"область"},
		{"English":"book", "Russian":"книга"},
		{"English":"business", "Russian":"бизнес"},
		{"English":"child", "Russian":"ребенок"},
		{"English":"company", "Russian":"компания"},
		{"English":"country", "Russian":"страна"},
		{"English":"day", "Russian":"день"},
		{"English":"eye", "Russian":"глаз"},
		{"English":"fact", "Russian":"факт"},
		{"English":"family", "Russian":"семья"},
		{"English":"government", "Russian":"правительство"},
		{"English":"group", "Russian":"группа"},
		{"English":"hand", "Russian":"рука"},
		{"English":"home", "Russian":"дом"},
		{"English":"job", "Russian":"работа"},
		{"English":"life", "Russian":"жизнь"},
		{"English":"lot", "Russian":"много"},
		{"English":"man", "Russian":"мужчина"},
		{"English":"money", "Russian":"деньги"},
		{"English":"month", "Russian":"месяц"},
		{"English":"mother", "Russian":"мама"},
		{"English":"Mr", "Russian":"Г-н"},
		{"English":"night", "Russian":"ночь"},
		{"English":"number", "Russian":"номер"},
		{"English":"part", "Russian":"часть"},
		{"English":"people", "Russian":"люди"},
		{"English":"place", "Russian":"место"},
		{"English":"point", "Russian":"точка"},
		{"English":"problem", "Russian":"проблема"},
		{"English":"program", "Russian":"программа"},
		{"English":"question", "Russian":"вопрос"},
		{"English":"right", "Russian":"право"},
		{"English":"room", "Russian":"комната"},
		{"English":"school", "Russian":"школа"},
		{"English":"state", "Russian":"государство"},
		{"English":"story", "Russian":"история"},
		{"English":"student", "Russian":"студент"},
		{"English":"study", "Russian":"изучать"},
		{"English":"system", "Russian":"система"},
		{"English":"thing", "Russian":"вещь"},
		{"English":"time", "Russian":"время"},
		{"English":"water", "Russian":"вода"},
		{"English":"way", "Russian":"путь"},
		{"English":"week", "Russian":"неделя"},
		{"English":"woman", "Russian":"женщина"},
		{"English":"word", "Russian":"слово"},
		{"English":"work", "Russian":"работа"},
		{"English":"world", "Russian":"мир"},
		{"English":"year", "Russian":"год"}
	]
}