
{
	"IdLearnSet":10,
	"Words":
	[
		{"English":"ask", "Russian":"спрашивать"},
		{"English":"be", "Russian":"быть"},
		{"English":"become", "Russian":"становиться"},
		{"English":"begin", "Russian":"начать"},
		{"English":"call", "Russian":"вызов"},
		{"English":"can", "Russian":"мочь"},
		{"English":"come", "Russian":"приходить"},
		{"English":"could", "Russian":"мог"},
		{"English":"do", "Russian":"делать"},
		{"English":"feel", "Russian":"чувствовать"},
		{"English":"find", "Russian":"находить"},
		{"English":"get", "Russian":"получить"},
		{"English":"give", "Russian":"дать"},
		{"English":"go", "Russian":"идти"},
		{"English":"have", "Russian":"иметь"},
		{"English":"hear", "Russian":"слышать"},
		{"English":"help", "Russian":"помощь"},
		{"English":"keep", "Russian":"держать"},
		{"English":"know", "Russian":"знать"},
		{"English":"leave", "Russian":"покидать"},
		{"English":"let", "Russian":"позволять"},
		{"English":"like", "Russian":"любить"},
		{"English":"live", "Russian":"жить"},
		{"English":"look", "Russian":"смотреть"},
		{"English":"make", "Russian":"делать"},
		{"English":"may", "Russian":"мочь"},
		{"English":"mean", "Russian":"означать"},
		{"English":"might", "Russian":"мочь"},
		{"English":"move", "Russian":"двигаться"},
		{"English":"need", "Russian":"нуждаться"},
		{"English":"play", "Russian":"играть"},
		{"English":"put", "Russian":"класть"},
		{"English":"run", "Russian":"бежать"},
		{"English":"say", "Russian":"сказать"},
		{"English":"see", "Russian":"видеть"},
		{"English":"seem", "Russian":"казаться"},
		{"English":"should", "Russian":"должен"},
		{"English":"show", "Russian":"показывать"},
		{"English":"start", "Russian":"начать"},
		{"English":"take", "Russian":"брать"},
		{"English":"talk", "Russian":"говорить"},
		{"English":"tell", "Russian":"рассказывать"},
		{"English":"think", "Russian":"думать"},
		{"English":"try", "Russian":"пробовать"},
		{"English":"use", "Russian":"использовать"},
		{"English":"want", "Russian":"хотеть"},
		{"English":"will", "Russian":"будет"},
		{"English":"work", "Russian":"работать"},
		{"English":"would", "Russian":"было бы"}
	]
}