
{
	"IdLearnSet":7,
	"Words":
	[
		{"English":"be", "Russian":"быть"},
		{"English":"and", "Russian":"и"},
		{"English":"in", "Russian":"в"},
		{"English":"to", "Russian":"к"},
		{"English":"have", "Russian":"иметь"},
		{"English":"it", "Russian":"это"},
		{"English":"for", "Russian":"для"},
		{"English":"I", "Russian":"я"},
		{"English":"that", "Russian":"тот"},
		{"English":"you", "Russian":"ты, вы"},
		{"English":"he", "Russian":"он"},
		{"English":"on", "Russian":"на"},
		{"English":"with", "Russian":"с"},
		{"English":"do", "Russian":"делать"},
		{"English":"at", "Russian":"у"},
		{"English":"by", "Russian":"к"},
		{"English":"not", "Russian":"не"},
		{"English":"this", "Russian":"это"},
		{"English":"but", "Russian":"но"},
		{"English":"from", "Russian":"от"},
		{"English":"they", "Russian":"они"},
		{"English":"his", "Russian":"его"},
		{"English":"she", "Russian":"она"},
		{"English":"or", "Russian":"или"},
		{"English":"which", "Russian":"который"},
		{"English":"as", "Russian":"как"},
		{"English":"we", "Russian":"мы"},
		{"English":"say", "Russian":"сказать"},
		{"English":"would", "Russian":"бы"},
		{"English":"can", "Russian":"уметь, мочь"},
		{"English":"if", "Russian":"если"},
		{"English":"their", "Russian":"их"},
		{"English":"go", "Russian":"ходить, идти"},
		{"English":"what", "Russian":"что"},
		{"English":"there", "Russian":"там"},
		{"English":"all", "Russian":"все"},
		{"English":"get", "Russian":"получать"},
		{"English":"her", "Russian":"ее"},
		{"English":"make", "Russian":"делать"},
		{"English":"who", "Russian":"кто"},
		{"English":"out", "Russian":"вне"},
		{"English":"up", "Russian":"вверх"},
		{"English":"see", "Russian":"видеть"},
		{"English":"know", "Russian":"знать"},
		{"English":"time", "Russian":"время"},
		{"English":"take", "Russian":"брать"},
		{"English":"them", "Russian":"им"},
		{"English":"some", "Russian":"некоторые"},
		{"English":"could", "Russian":"мог"},
		{"English":"so", "Russian":"так"},
		{"English":"him", "Russian":"ему"},
		{"English":"year", "Russian":"год"},
		{"English":"into", "Russian":"в"},
		{"English":"its", "Russian":"его"},
		{"English":"then", "Russian":"затем"},
		{"English":"think", "Russian":"думать"},
		{"English":"my", "Russian":"мой"},
		{"English":"come", "Russian":"приходить"},
		{"English":"than", "Russian":"чем"},
		{"English":"more", "Russian":"больше"},
		{"English":"about", "Russian":"о"},
		{"English":"now", "Russian":"сейчас"},
		{"English":"last", "Russian":"последний"},
		{"English":"your", "Russian":"твой, ваш"},
		{"English":"me", "Russian":"мне"},
		{"English":"no", "Russian":"нет"},
		{"English":"other", "Russian":"другой"},
		{"English":"give", "Russian":"дать"},
		{"English":"just", "Russian":"просто"},
		{"English":"should", "Russian":"следует"},
		{"English":"these", "Russian":"эти"},
		{"English":"people", "Russian":"люди"},
		{"English":"also", "Russian":"также"},
		{"English":"well", "Russian":"хорошо"},
		{"English":"any", "Russian":"любой"},
		{"English":"only", "Russian":"только; единственный"},
		{"English":"new", "Russian":"новый"},
		{"English":"very", "Russian":"очень"},
		{"English":"when", "Russian":"когда"},
		{"English":"may", "Russian":"мочь"},
		{"English":"way", "Russian":"путь, способ"},
		{"English":"look", "Russian":"смотреть; взгляд"},
		{"English":"like", "Russian":"любить, нравиться; как"},
		{"English":"use", "Russian":"использовать"},
		{"English":"such", "Russian":"такой"},
		{"English":"how", "Russian":"как"},
		{"English":"because", "Russian":"потому что"},
		{"English":"good", "Russian":"хороший"},
		{"English":"find", "Russian":"найти"},
		{"English":"man", "Russian":"человек, мужчина"},
		{"English":"our", "Russian":"наш"},
		{"English":"want", "Russian":"хотеть"},
		{"English":"day", "Russian":"день"},
		{"English":"between", "Russian":"между"},
		{"English":"even", "Russian":"даже"},
		{"English":"many", "Russian":"много (для исчисляемых)"},
		{"English":"those", "Russian":"те"},
		{"English":"after", "Russian":"после"},
		{"English":"down", "Russian":"внизу"},
		{"English":"yeah", "Russian":"да"},
		{"English":"thing", "Russian":"вещь"},
		{"English":"tell", "Russian":"сказать (кому-то)"},
		{"English":"through", "Russian":"сквозь"},
		{"English":"back", "Russian":"назад; спина"},
		{"English":"still", "Russian":"все еще; тихий"},
		{"English":"must", "Russian":"должен"},
		{"English":"child", "Russian":"ребенок"},
		{"English":"here", "Russian":"здесь"},
		{"English":"over", "Russian":"над"},
		{"English":"too", "Russian":"тоже; слишком"},
		{"English":"put", "Russian":"положить"},
		{"English":"own", "Russian":"собственный"},
		{"English":"work", "Russian":"работа"},
		{"English":"become", "Russian":"становиться"},
		{"English":"old", "Russian":"старый"},
		{"English":"government", "Russian":"правительство"},
		{"English":"mean", "Russian":"иметь в виду"},
		{"English":"part", "Russian":"часть"},
		{"English":"leave", "Russian":"покинуть"},
		{"English":"life", "Russian":"жизнь"},
		{"English":"great", "Russian":"отличный"},
		{"English":"where", "Russian":"где"},
		{"English":"case", "Russian":"случай"},
		{"English":"woman", "Russian":"женщина"},
		{"English":"seem", "Russian":"казаться"},
		{"English":"same", "Russian":"тот же самый"},
		{"English":"us", "Russian":"нас"},
		{"English":"need", "Russian":"нужда; нужно"},
		{"English":"feel", "Russian":"чувствовать"},
		{"English":"each", "Russian":"каждый"},
		{"English":"much", "Russian":"много, очень"},
		{"English":"ask", "Russian":"спрашивать"},
		{"English":"group", "Russian":"группа"},
		{"English":"number", "Russian":"число, номер"},
		{"English":"yes", "Russian":"да"},
		{"English":"however", "Russian":"однако"},
		{"English":"another", "Russian":"другой"},
		{"English":"again", "Russian":"снова"},
		{"English":"world", "Russian":"мир"},
		{"English":"area", "Russian":"территория, площадь"},
		{"English":"show", "Russian":"шоу, показывать"},
		{"English":"course", "Russian":"курс"},
		{"English":"under", "Russian":"под"},
		{"English":"problem", "Russian":"проблема"},
		{"English":"against", "Russian":"против"},
		{"English":"never", "Russian":"никогда"},
		{"English":"most", "Russian":"самый"},
		{"English":"service", "Russian":"служба"},
		{"English":"try", "Russian":"стараться"},
		{"English":"call", "Russian":"звонок; звать"},
		{"English":"hand", "Russian":"рука"},
		{"English":"party", "Russian":"вечеринка"},
		{"English":"high", "Russian":"высоко, высокий"},
		{"English":"something", "Russian":"что-то"},
		{"English":"school", "Russian":"школа"},
		{"English":"small", "Russian":"маленький"},
		{"English":"place", "Russian":"место"},
		{"English":"before", "Russian":"до"},
		{"English":"why", "Russian":"почему"},
		{"English":"while", "Russian":"в то время как, пока"},
		{"English":"away", "Russian":"вне"},
		{"English":"keep", "Russian":"хранить, держать, продолжать"},
		{"English":"point", "Russian":"точка; смысл"},
		{"English":"house", "Russian":"дом"},
		{"English":"different", "Russian":"различный"},
		{"English":"country", "Russian":"страна; сельская местность"},
		{"English":"really", "Russian":"в самом деле"},
		{"English":"provide", "Russian":"обеспечить"},
		{"English":"week", "Russian":"неделя"},
		{"English":"hold", "Russian":"держать, проводить"},
		{"English":"large", "Russian":"большой"},
		{"English":"member", "Russian":"член"},
		{"English":"off", "Russian":"от"},
		{"English":"always", "Russian":"всегда"},
		{"English":"next", "Russian":"следующий"},
		{"English":"follow", "Russian":"следовать"},
		{"English":"without", "Russian":"без"},
		{"English":"turn", "Russian":"очередность; поворачивать"},
		{"English":"end", "Russian":"конец"},
		{"English":"local", "Russian":"местный"},
		{"English":"during", "Russian":"в течение"},
		{"English":"bring", "Russian":"нести"},
		{"English":"word", "Russian":"слово"},
		{"English":"begin", "Russian":"начинать"},
		{"English":"although", "Russian":"хотя"},
		{"English":"example", "Russian":"пример"},
		{"English":"family", "Russian":"семья"},
		{"English":"rather", "Russian":"скорее"},
		{"English":"fact", "Russian":"факт"},
		{"English":"social", "Russian":"общественный"},
		{"English":"write", "Russian":"писать"},
		{"English":"state", "Russian":"государство, штат; утверждать"},
		{"English":"percent", "Russian":"процент"},
		{"English":"quite", "Russian":"довольно"},
		{"English":"both", "Russian":"оба"},
		{"English":"start", "Russian":"старт"},
		{"English":"run", "Russian":"бег, бежать"},
		{"English":"long", "Russian":"длинный"},
		{"English":"right", "Russian":"правый; право"},
		{"English":"set", "Russian":"набор; установить"},
		{"English":"help", "Russian":"помогать, помощь"},
		{"English":"every", "Russian":"каждый"},
		{"English":"home", "Russian":"дом, домашний"},
		{"English":"month", "Russian":"месяц"},
		{"English":"side", "Russian":"сторона"},
		{"English":"night", "Russian":"ночь"},
		{"English":"important", "Russian":"важный"},
		{"English":"eye", "Russian":"глаз"},
		{"English":"head", "Russian":"возглавлять; голова"},
		{"English":"question", "Russian":"вопрос"},
		{"English":"play", "Russian":"играть"},
		{"English":"power", "Russian":"власть, сила"},
		{"English":"money", "Russian":"деньги"},
		{"English":"change", "Russian":"изменение; сдача; менять"},
		{"English":"move", "Russian":"двигаться"},
		{"English":"interest", "Russian":"интерес; процент прибыли"},
		{"English":"order", "Russian":"приказ; порядок; заказывать"},
		{"English":"book", "Russian":"книга; заказать"},
		{"English":"often", "Russian":"часто"},
		{"English":"young", "Russian":"молодой"},
		{"English":"national", "Russian":"национальный"},
		{"English":"pay", "Russian":"платить"},
		{"English":"hear", "Russian":"слышать"},
		{"English":"room", "Russian":"комната"},
		{"English":"whether", "Russian":"ли"},
		{"English":"water", "Russian":"вода"},
		{"English":"form", "Russian":"форма; бланк"},
		{"English":"car", "Russian":"автомобиль"},
		{"English":"others", "Russian":"другие"},
		{"English":"yet", "Russian":"еще (не); однако"},
		{"English":"perhaps", "Russian":"возможно"},
		{"English":"meet", "Russian":"встретить, познакомиться"},
		{"English":"till", "Russian":"до"},
		{"English":"though", "Russian":"хотя"},
		{"English":"policy", "Russian":"политика"},
		{"English":"include", "Russian":"включать (в себя)"},
		{"English":"believe", "Russian":"верить"},
		{"English":"already", "Russian":"уже"},
		{"English":"possible", "Russian":"возможный"},
		{"English":"nothing", "Russian":"ничего"},
		{"English":"line", "Russian":"линия"},
		{"English":"allow", "Russian":"позволять"},
		{"English":"effect", "Russian":"эффект"},
		{"English":"big", "Russian":"большой"},
		{"English":"late", "Russian":"поздний"},
		{"English":"lead", "Russian":"руководство; вести"},
		{"English":"stand", "Russian":"стоять; стойка"},
		{"English":"idea", "Russian":"идея"},
		{"English":"study", "Russian":"учеба"},
		{"English":"lot", "Russian":"много"},
		{"English":"live", "Russian":"жить"},
		{"English":"job", "Russian":"работа"},
		{"English":"since", "Russian":"с (тех пор как)"},
		{"English":"name", "Russian":"имя, называть"},
		{"English":"result", "Russian":"результат"},
		{"English":"body", "Russian":"тело"},
		{"English":"happen", "Russian":"случаться"},
		{"English":"friend", "Russian":"друг"},
		{"English":"least", "Russian":"наименьший"},
		{"English":"almost", "Russian":"почти"},
		{"English":"carry", "Russian":"нести"},
		{"English":"authority", "Russian":"власть"},
		{"English":"early", "Russian":"рано"},
		{"English":"view", "Russian":"взгляд; обозревать"},
		{"English":"himself", "Russian":"(он) сам"},
		{"English":"public", "Russian":"общественный; народ, публика"},
		{"English":"usually", "Russian":"обычно"},
		{"English":"together", "Russian":"вместе"},
		{"English":"talk", "Russian":"беседа, беседовать"},
		{"English":"report", "Russian":"доклад; сообщать"},
		{"English":"face", "Russian":"лицо; стоять лицом к"},
		{"English":"sit", "Russian":"сидеть"},
		{"English":"appear", "Russian":"появляться"},
		{"English":"continue", "Russian":"продолжать"},
		{"English":"able", "Russian":"способный"},
		{"English":"political", "Russian":"политический"},
		{"English":"hour", "Russian":"час"},
		{"English":"rate", "Russian":"пропорция; ставка"},
		{"English":"law", "Russian":"закон"},
		{"English":"door", "Russian":"дверь"},
		{"English":"company", "Russian":"компания"},
		{"English":"court", "Russian":"суд"},
		{"English":"fuck", "Russian":"трахаться"},
		{"English":"little", "Russian":"маленький, немного"},
		{"English":"because of", "Russian":"из-за"},
		{"English":"office", "Russian":"офис"},
		{"English":"let", "Russian":"позволить"},
		{"English":"war", "Russian":"война"},
		{"English":"reason", "Russian":"причина"},
		{"English":"less", "Russian":"менее"},
		{"English":"subject", "Russian":"предмет"},
		{"English":"person", "Russian":"лицо; человек"},
		{"English":"term", "Russian":"термин; срок"},
		{"English":"full", "Russian":"полный"},
		{"English":"sort", "Russian":"сорт, вид; сортировать"},
		{"English":"require", "Russian":"требовать"},
		{"English":"suggest", "Russian":"предлагать, предполагать"},
		{"English":"far", "Russian":"далеко"},
		{"English":"towards", "Russian":"к"},
		{"English":"anything", "Russian":"ничего"},
		{"English":"period", "Russian":"период"},
		{"English":"read", "Russian":"читать"},
		{"English":"society", "Russian":"общество"},
		{"English":"process", "Russian":"процесс"},
		{"English":"mother", "Russian":"мать"},
		{"English":"offer", "Russian":"предложение, предлагать"},
		{"English":"voice", "Russian":"голос"},
		{"English":"once", "Russian":"как только; однажды"},
		{"English":"police", "Russian":"полиция"},
		{"English":"lose", "Russian":"терять"},
		{"English":"add", "Russian":"добавлять"},
		{"English":"probably", "Russian":"вероятно"},
		{"English":"expect", "Russian":"ожидать"},
		{"English":"ever", "Russian":"коогда-нибудь"},
		{"English":"price", "Russian":"цена"},
		{"English":"action", "Russian":"действие"},
		{"English":"issue", "Russian":"выпуск"},
		{"English":"remember", "Russian":"помнить"},
		{"English":"position", "Russian":"позиция"},
		{"English":"low", "Russian":"низкий"},
		{"English":"matter", "Russian":"дело, вопрос, факты; иметь значение"},
		{"English":"community", "Russian":"община"},
		{"English":"remain", "Russian":"оставаться"},
		{"English":"figure", "Russian":"цифра"},
		{"English":"type", "Russian":"тип"},
		{"English":"actually", "Russian":"вообще-то"},
		{"English":"education", "Russian":"образование"},
		{"English":"fall", "Russian":"падать; упадок"},
		{"English":"speak", "Russian":"говорить"},
		{"English":"few", "Russian":"мало"},
		{"English":"today", "Russian":"сегодня"},
		{"English":"enough", "Russian":"достаточно"},
		{"English":"open", "Russian":"открытый, открывать"},
		{"English":"bad", "Russian":"плохой"},
		{"English":"buy", "Russian":"покупать"},
		{"English":"minute", "Russian":"минута"},
		{"English":"moment", "Russian":"момент"},
		{"English":"girl", "Russian":"девочка, девушка"},
		{"English":"age", "Russian":"возраст"},
		{"English":"centre", "Russian":"центр"},
		{"English":"stop", "Russian":"остановка; остановить(-ся)"},
		{"English":"control", "Russian":"контроль, контролировать"},
		{"English":"send", "Russian":"посылать"},
		{"English":"health", "Russian":"здоровье"},
		{"English":"decide", "Russian":"решать"},
		{"English":"main", "Russian":"главный"},
		{"English":"win", "Russian":"победить; победа"},
		{"English":"wound", "Russian":"рана; ранить"},
		{"English":"understand", "Russian":"понимать"},
		{"English":"develop", "Russian":"развивать"},
		{"English":"class", "Russian":"класс"},
		{"English":"industry", "Russian":"промышленность"},
		{"English":"receive", "Russian":"получать"},
		{"English":"several", "Russian":"несколько"},
		{"English":"return", "Russian":"возвращение, возвращаться"},
		{"English":"build", "Russian":"строить"},
		{"English":"spend", "Russian":"проводить (время)"},
		{"English":"force", "Russian":"сила, принуждать"},
		{"English":"condition", "Russian":"условие"},
		{"English":"itself", "Russian":"(он) сам"},
		{"English":"paper", "Russian":"бумага; газета"},
		{"English":"themselves", "Russian":"(они) сами"},
		{"English":"major", "Russian":"главный"},
		{"English":"describe", "Russian":"описывать"},
		{"English":"agree", "Russian":"соглашаться"},
		{"English":"economic", "Russian":"экономический"},
		{"English":"upon", "Russian":"на"},
		{"English":"learn", "Russian":"учить"},
		{"English":"general", "Russian":"генерал; общий"},
		{"English":"century", "Russian":"век"},
		{"English":"therefore", "Russian":"поэтому"},
		{"English":"father", "Russian":"отец"},
		{"English":"section", "Russian":"раздел"},
		{"English":"patient", "Russian":"терпеливый; пациент"},
		{"English":"around", "Russian":"вокруг"},
		{"English":"activity", "Russian":"мероприятие"},
		{"English":"road", "Russian":"дорога"},
		{"English":"table", "Russian":"стол"},
		{"English":"cow", "Russian":"корова"},
		{"English":"including", "Russian":"включающий"},
		{"English":"church", "Russian":"церковь"},
		{"English":"reach", "Russian":"достигать"},
		{"English":"real", "Russian":"реальный"},
		{"English":"lie", "Russian":"лгать"},
		{"English":"mind", "Russian":"ум; возражать"},
		{"English":"likely", "Russian":"вероятный"},
		{"English":"among", "Russian":"среди"},
		{"English":"team", "Russian":"команда"},
		{"English":"death", "Russian":"смерть"},
		{"English":"soon", "Russian":"скоро"},
		{"English":"act", "Russian":"акт, действие; действовать"},
		{"English":"sense", "Russian":"смысл; чувство; чувствовать"},
		{"English":"staff", "Russian":"персонал"},
		{"English":"certain", "Russian":"определенный"},
		{"English":"student", "Russian":"студент"},
		{"English":"half", "Russian":"половина"},
		{"English":"language", "Russian":"язык"},
		{"English":"walk", "Russian":"прогулка; ходить (пешком)"},
		{"English":"die", "Russian":"умереть"},
		{"English":"special", "Russian":"особый"},
		{"English":"difficult", "Russian":"трудный"},
		{"English":"international", "Russian":"международный"},
		{"English":"department", "Russian":"отделение"},
		{"English":"management", "Russian":"управление"},
		{"English":"morning", "Russian":"утро"},
		{"English":"draw", "Russian":"рисовать (карандашом)"},
		{"English":"hope", "Russian":"надежда; надеяться"},
		{"English":"across", "Russian":"через"},
		{"English":"plan", "Russian":"план, планировать"},
		{"English":"product", "Russian":"продукт"},
		{"English":"city", "Russian":"город"},
		{"English":"committee", "Russian":"комитет"},
		{"English":"ground", "Russian":"земля"},
		{"English":"letter", "Russian":"письмо; буква"},
		{"English":"create", "Russian":"создавать"},
		{"English":"evidence", "Russian":"свидетельство"},
		{"English":"foot", "Russian":"нога"},
		{"English":"clear", "Russian":"ясный, очищать"},
		{"English":"boy", "Russian":"мальчик"},
		{"English":"game", "Russian":"игра"},
		{"English":"food", "Russian":"еда"},
		{"English":"role", "Russian":"роль"},
		{"English":"practice", "Russian":"практика"},
		{"English":"bank", "Russian":"банк; берег"},
		{"English":"else", "Russian":"еще"},
		{"English":"support", "Russian":"поддержка, поддерживать"},
		{"English":"sell", "Russian":"продавать"},
		{"English":"event", "Russian":"событие"},
		{"English":"building", "Russian":"здание"},
		{"English":"behind", "Russian":"за, сзади"},
		{"English":"sure", "Russian":"уверенный"},
		{"English":"pass", "Russian":"передавать, проходить"},
		{"English":"black", "Russian":"черный"},
		{"English":"stage", "Russian":"стадия"},
		{"English":"meeting", "Russian":"встреча"},
		{"English":"hi", "Russian":"привет"},
		{"English":"sometimes", "Russian":"иногда"},
		{"English":"thus", "Russian":"таким образом"},
		{"English":"accept", "Russian":"допускать"},
		{"English":"available", "Russian":"наличный"},
		{"English":"town", "Russian":"город"},
		{"English":"art", "Russian":"искусство"},
		{"English":"further", "Russian":"дальнейший"},
		{"English":"club", "Russian":"клуб"},
		{"English":"arm", "Russian":"рука"},
		{"English":"history", "Russian":"история"},
		{"English":"parent", "Russian":"родитель"},
		{"English":"land", "Russian":"земля; приземляться"},
		{"English":"trade", "Russian":"торговля, торговать"},
		{"English":"watch", "Russian":"часы; наблюдать"},
		{"English":"white", "Russian":"белый"},
		{"English":"situation", "Russian":"ситуация"},
		{"English":"whose", "Russian":"чей"},
		{"English":"ago", "Russian":"назад"},
		{"English":"teacher", "Russian":"учитель"},
		{"English":"record", "Russian":"запись; записывать"},
		{"English":"manager", "Russian":"управляющий, менеджер"},
		{"English":"relation", "Russian":"связь, отношение"},
		{"English":"common", "Russian":"общий"},
		{"English":"system", "Russian":"система"},
		{"English":"strong", "Russian":"сильный"},
		{"English":"whole", "Russian":"целый"},
		{"English":"field", "Russian":"поле"},
		{"English":"free", "Russian":"свободный"},
		{"English":"break", "Russian":"ломать; перерыв"},
		{"English":"yesterday", "Russian":"вчера"},
		{"English":"window", "Russian":"окно"},
		{"English":"account", "Russian":"счет"},
		{"English":"explain", "Russian":"объяснять"},
		{"English":"stay", "Russian":"остановиться"},
		{"English":"wait", "Russian":"ждать"},
		{"English":"material", "Russian":"материал"},
		{"English":"air", "Russian":"воздух"},
		{"English":"wife", "Russian":"жена"},
		{"English":"cover", "Russian":"крышка, покрывать"},
		{"English":"apply", "Russian":"обращаться"},
		{"English":"love", "Russian":"любить, любовь"},
		{"English":"project", "Russian":"проект"},
		{"English":"raise", "Russian":"поднимать"},
		{"English":"sale", "Russian":"продажа"},
		{"English":"relationship", "Russian":"отношение"},
		{"English":"indeed", "Russian":"в самом деле"},
		{"English":"please", "Russian":"пожалуйста"},
		{"English":"light", "Russian":"светлый; легкий; свет"},
		{"English":"claim", "Russian":"требование, требовать"},
		{"English":"base", "Russian":"основа, база;базироваться"},
		{"English":"care", "Russian":"заботиться; забота, осторожность"},
		{"English":"someone", "Russian":"кто-то"},
		{"English":"everything", "Russian":"всё"},
		{"English":"certainly", "Russian":"конечно"},
		{"English":"rule", "Russian":"правило; управлять"},
		{"English":"cut", "Russian":"резать"},
		{"English":"grow", "Russian":"расти, выращивать"},
		{"English":"similar", "Russian":"подобный"},
		{"English":"story", "Russian":"история, рассказ"},
		{"English":"quality", "Russian":"качество"},
		{"English":"tax", "Russian":"налог"},
		{"English":"worker", "Russian":"рабочий"},
		{"English":"nature", "Russian":"природа"},
		{"English":"structure", "Russian":"структура"},
		{"English":"necessary", "Russian":"необходимый"},
		{"English":"pound", "Russian":"фунт"},
		{"English":"method", "Russian":"метод"},
		{"English":"unit", "Russian":"часть"},
		{"English":"central", "Russian":"центральный"},
		{"English":"bed", "Russian":"кровать"},
		{"English":"union", "Russian":"союз"},
		{"English":"movement", "Russian":"движение"},
		{"English":"board", "Russian":"доска; совет"},
		{"English":"true", "Russian":"правдивый"},
		{"English":"especially", "Russian":"особенно"},
		{"English":"short", "Russian":"короткий"},
		{"English":"personal", "Russian":"личный"},
		{"English":"detail", "Russian":"деталь"},
		{"English":"model", "Russian":"модель"},
		{"English":"bear", "Russian":"медведь;носить; рождать"},
		{"English":"single", "Russian":"одинокий"},
		{"English":"join", "Russian":"присоединяться"},
		{"English":"reduce", "Russian":"сокращать"},
		{"English":"establish", "Russian":"учреждать"},
		{"English":"herself", "Russian":"(она) сама"},
		{"English":"wall", "Russian":"стена"},
		{"English":"easy", "Russian":"легкий"},
		{"English":"private", "Russian":"частный"},
		{"English":"computer", "Russian":"компьютер"},
		{"English":"former", "Russian":"бывший"},
		{"English":"hospital", "Russian":"больница"},
		{"English":"chapter", "Russian":"глава"},
		{"English":"scheme", "Russian":"схема, план"},
		{"English":"bye", "Russian":"пока"},
		{"English":"consider", "Russian":"полагать"},
		{"English":"council", "Russian":"совет"},
		{"English":"development", "Russian":"развитие"},
		{"English":"experience", "Russian":"опыт"},
		{"English":"information", "Russian":"информация"},
		{"English":"involve", "Russian":"вовлекать"},
		{"English":"theory", "Russian":"теория"},
		{"English":"within", "Russian":"в"},
		{"English":"choose", "Russian":"выбирать"},
		{"English":"wish", "Russian":"желать; желание"},
		{"English":"property", "Russian":"собственность"},
		{"English":"achieve", "Russian":"достигать"},
		{"English":"financial", "Russian":"финансовый"},
		{"English":"poor", "Russian":"бедный"},
		{"English":"blow", "Russian":"дуть"},
		{"English":"charge", "Russian":"ответственность; загружать"},
		{"English":"director", "Russian":"директор"},
		{"English":"drive", "Russian":"водить (машину); катание, езда"},
		{"English":"approach", "Russian":"подход, приближаться"},
		{"English":"chance", "Russian":"шанс"},
		{"English":"application", "Russian":"приложение"},
		{"English":"seek", "Russian":"искать"},
		{"English":"cool", "Russian":"крутой; прохладный"},
		{"English":"foreign", "Russian":"иностранный"},
		{"English":"along", "Russian":"вдоль"},
		{"English":"top", "Russian":"верхний, верх"},
		{"English":"amount", "Russian":"количество"},
		{"English":"son", "Russian":"сын"},
		{"English":"operation", "Russian":"операция"},
		{"English":"fail", "Russian":"потерпеть неудачу"},
		{"English":"human", "Russian":"человеческий,человек"},
		{"English":"opportunity", "Russian":"возможность"},
		{"English":"simple", "Russian":"простой"},
		{"English":"leader", "Russian":"лидер"},
		{"English":"level", "Russian":"уровень"},
		{"English":"production", "Russian":"продукция"},
		{"English":"value", "Russian":"стоимость"},
		{"English":"firm", "Russian":"крепкий; фирма"},
		{"English":"picture", "Russian":"картина"},
		{"English":"source", "Russian":"источник"},
		{"English":"security", "Russian":"безопасность"},
		{"English":"serve", "Russian":"служить"},
		{"English":"according", "Russian":"соответствие"},
		{"English":"business", "Russian":"дело"},
		{"English":"decision", "Russian":"решение"},
		{"English":"contract", "Russian":"контакт"},
		{"English":"wide", "Russian":"широкий"},
		{"English":"agreement", "Russian":"соглашение"},
		{"English":"kill", "Russian":"убивать"},
		{"English":"site", "Russian":"место"},
		{"English":"either", "Russian":"один из двух; тоже (не)"},
		{"English":"various", "Russian":"разнообразный"},
		{"English":"screw", "Russian":"закручивать"},
		{"English":"test", "Russian":"тест; проверять"},
		{"English":"eat", "Russian":"кушать"},
		{"English":"close", "Russian":"близкий;закрывать"},
		{"English":"represent", "Russian":"представлять"},
		{"English":"colour", "Russian":"цвет"},
		{"English":"shop", "Russian":"магазин"},
		{"English":"benefit", "Russian":"выгода"},
		{"English":"animal", "Russian":"животное"},
		{"English":"heart", "Russian":"сердце"},
		{"English":"election", "Russian":"выборы"},
		{"English":"purpose", "Russian":"цель"},
		{"English":"due", "Russian":"обязанный"},
		{"English":"secretary", "Russian":"секретарь"},
		{"English":"rise", "Russian":"восход; подниматься"},
		{"English":"date", "Russian":"дата, датировать"},
		{"English":"hard", "Russian":"упорно; тяжелый, упорный"},
		{"English":"music", "Russian":"музыка"},
		{"English":"hair", "Russian":"волосы"},
		{"English":"prepare", "Russian":"приготовить"},
		{"English":"anyone", "Russian":"кто-нибудь"},
		{"English":"pattern", "Russian":"модель"},
		{"English":"manage", "Russian":"управлять"},
		{"English":"piece", "Russian":"кусок"},
		{"English":"discuss", "Russian":"обсуждать"},
		{"English":"prove", "Russian":"даказывать"},
		{"English":"front", "Russian":"передняя часть, передний"},
		{"English":"evening", "Russian":"вечер"},
		{"English":"royal", "Russian":"королевский"},
		{"English":"tree", "Russian":"дерево"},
		{"English":"population", "Russian":"население"},
		{"English":"fine", "Russian":"прекрасный"},
		{"English":"plant", "Russian":"растение; завод; сажать"},
		{"English":"pressure", "Russian":"давление"},
		{"English":"response", "Russian":"ответ"},
		{"English":"catch", "Russian":"хватать"},
		{"English":"street", "Russian":"улица"},
		{"English":"knowledge", "Russian":"знание"},
		{"English":"despite", "Russian":"несмотря на"},
		{"English":"design", "Russian":"дизайн, разрабатывать"},
		{"English":"kind", "Russian":"вид; тип; добрый"},
		{"English":"page", "Russian":"страница"},
		{"English":"enjoy", "Russian":"наслаждаться"},
		{"English":"individual", "Russian":"личный;частное лицо"},
		{"English":"rest", "Russian":"остаток; отдых; отдыхать"},
		{"English":"instead", "Russian":"вместо"},
		{"English":"wear", "Russian":"носить"},
		{"English":"basis", "Russian":"базис"},
		{"English":"size", "Russian":"размер"},
		{"English":"fire", "Russian":"огонь, пожар; поджигать"},
		{"English":"series", "Russian":"ряд, серия"},
		{"English":"success", "Russian":"успех"},
		{"English":"natural", "Russian":"естественный"},
		{"English":"wrong", "Russian":"неправильный"},
		{"English":"near", "Russian":"около"},
		{"English":"round", "Russian":"вокруг; круглый; круг"},
		{"English":"thought", "Russian":"мысль"},
		{"English":"list", "Russian":"список"},
		{"English":"argue", "Russian":"спорить"},
		{"English":"final", "Russian":"окончательный"},
		{"English":"future", "Russian":"будущее"},
		{"English":"introduce", "Russian":"знакомить"},
		{"English":"enter", "Russian":"входить"},
		{"English":"space", "Russian":"космос; место"},
		{"English":"arrive", "Russian":"прибывать"},
		{"English":"ensure", "Russian":"обеспечивать"},
		{"English":"statement", "Russian":"утверждение"},
		{"English":"balcony", "Russian":"балкон"},
		{"English":"attention", "Russian":"внимание"},
		{"English":"principle", "Russian":"принцип"},
		{"English":"pull", "Russian":"тянуть"},
		{"English":"doctor", "Russian":"доктор"},
		{"English":"choice", "Russian":"выбор"},
		{"English":"refer", "Russian":"ссылаться"},
		{"English":"feature", "Russian":"особенность, функция"},
		{"English":"couple", "Russian":"пара"},
		{"English":"step", "Russian":"шаг; шагать"},
		{"English":"following", "Russian":"следующий"},
		{"English":"thank", "Russian":"благодарить"},
		{"English":"machine", "Russian":"машина"},
		{"English":"income", "Russian":"доход"},
		{"English":"training", "Russian":"тренировка"},
		{"English":"present", "Russian":"подарок; дарить; настоящий"},
		{"English":"association", "Russian":"ассоциация"},
		{"English":"film", "Russian":"фильм; пленка"},
		{"English":"difference", "Russian":"различие"},
		{"English":"fucking", "Russian":"проклятый"},
		{"English":"region", "Russian":"регион"},
		{"English":"effort", "Russian":"усилие"},
		{"English":"player", "Russian":"игрок"},
		{"English":"everyone", "Russian":"каждый"},
		{"English":"village", "Russian":"деревня"},
		{"English":"organisation", "Russian":"организация"},
		{"English":"whatever", "Russian":"что бы ни было"},
		{"English":"news", "Russian":"новости"},
		{"English":"nice", "Russian":"замечательный"},
		{"English":"modern", "Russian":"современный"},
		{"English":"cell", "Russian":"ячейка; камера"},
		{"English":"current", "Russian":"текущий"},
		{"English":"legal", "Russian":"законный"},
		{"English":"energy", "Russian":"энергия"},
		{"English":"finally", "Russian":"окончательно"},
		{"English":"degree", "Russian":"степень"},
		{"English":"mile", "Russian":"миля"},
		{"English":"means", "Russian":"средство"},
		{"English":"whom", "Russian":"кем"},
		{"English":"treatment", "Russian":"лечение"},
		{"English":"sound", "Russian":"звук, звучать"},
		{"English":"above", "Russian":"над"},
		{"English":"task", "Russian":"задание"},
		{"English":"red", "Russian":"красный"},
		{"English":"happy", "Russian":"счастливый"},
		{"English":"behaviour", "Russian":"поведение"},
		{"English":"identify", "Russian":"распознавать"},
		{"English":"resource", "Russian":"ресурс; источник"},
		{"English":"defence", "Russian":"защита"},
		{"English":"garden", "Russian":"сад"},
		{"English":"floor", "Russian":"пол; этаж"},
		{"English":"technology", "Russian":"технология"},
		{"English":"style", "Russian":"стиль"},
		{"English":"feeling", "Russian":"чувство"},
		{"English":"science", "Russian":"наука"},
		{"English":"relate", "Russian":"быть родственным"},
		{"English":"doubt", "Russian":"сомнение, сомневаться"},
		{"English":"ok", "Russian":"хорошо"},
		{"English":"produce", "Russian":"производить"},
		{"English":"horse", "Russian":"лошадь"},
		{"English":"answer", "Russian":"ответ"},
		{"English":"compare", "Russian":"сравнить"},
		{"English":"suffer", "Russian":"страдать"},
		{"English":"forward", "Russian":"вперед"},
		{"English":"announce", "Russian":"объявлять"},
		{"English":"user", "Russian":"пользователь"},
		{"English":"character", "Russian":"герой"},
		{"English":"risk", "Russian":"риск; рисковать"},
		{"English":"normal", "Russian":"обычный"},
		{"English":"myself", "Russian":"(я) сам"},
		{"English":"dog", "Russian":"собака"},
		{"English":"obtain", "Russian":"приобретать"},
		{"English":"quickly", "Russian":"быстро"},
		{"English":"army", "Russian":"армия"},
		{"English":"forget", "Russian":"забывать"},
		{"English":"ill", "Russian":"больной"},
		{"English":"station", "Russian":"станция, участок"},
		{"English":"glass", "Russian":"стекло; стакан"},
		{"English":"cup", "Russian":"кружка"},
		{"English":"previous", "Russian":"предыдущий"},
		{"English":"husband", "Russian":"муж"},
		{"English":"recently", "Russian":"недавно"},
		{"English":"publish", "Russian":"публиковать"},
		{"English":"serious", "Russian":"серьезный"},
		{"English":"anyway", "Russian":"в любом случае"},
		{"English":"visit", "Russian":"приходить в гости"},
		{"English":"capital", "Russian":"столица"},
		{"English":"sock", "Russian":"носок"},
		{"English":"note", "Russian":"заметка, отмечать"},
		{"English":"season", "Russian":"сезон; время года"},
		{"English":"argument", "Russian":"спор"},
		{"English":"listen", "Russian":"слушать"},
		{"English":"responsibility", "Russian":"ответственность"},
		{"English":"significant", "Russian":"значительный"},
		{"English":"deal", "Russian":"некоторое количество; иметь дело"},
		{"English":"prime", "Russian":"первичный"},
		{"English":"economy", "Russian":"экономика"},
		{"English":"finish", "Russian":"закончить"},
		{"English":"duty", "Russian":"долг"},
		{"English":"fight", "Russian":"бой, драка; сражаться"},
		{"English":"train", "Russian":"поезд;тренировать"},
		{"English":"maintain", "Russian":"обеспечивать"},
		{"English":"attempt", "Russian":"попытка"},
		{"English":"leg", "Russian":"нога"},
		{"English":"save", "Russian":"беречь"},
		{"English":"suddenly", "Russian":"вдруг"},
		{"English":"brother", "Russian":"брат"},
		{"English":"improve", "Russian":"улучшать"},
		{"English":"avoid", "Russian":"избегать"},
		{"English":"teenager", "Russian":"подросток"},
		{"English":"wonder", "Russian":"хотеть знать; удивление"},
		{"English":"fun", "Russian":"забава"},
		{"English":"title", "Russian":"название"},
		{"English":"post", "Russian":"почта; должность"},
		{"English":"hotel", "Russian":"гостиница"},
		{"English":"aspect", "Russian":"сторона, аспект"},
		{"English":"increase", "Russian":"увеличивать"},
		{"English":"surname", "Russian":"фамилия"},
		{"English":"industrial", "Russian":"промышленный"},
		{"English":"express", "Russian":"выражать"},
		{"English":"summer", "Russian":"лето"},
		{"English":"determine", "Russian":"определять"},
		{"English":"generally", "Russian":"в общем"},
		{"English":"daughter", "Russian":"дочь"},
		{"English":"exist", "Russian":"существовать"},
		{"English":"used to", "Russian":"бывало"},
		{"English":"share", "Russian":"делить; акция"},
		{"English":"baby", "Russian":"дитя"},
		{"English":"nearly", "Russian":"около"},
		{"English":"smile", "Russian":"улыбка, улыбаться"},
		{"English":"sorry", "Russian":"извини"},
		{"English":"sea", "Russian":"море"},
		{"English":"skill", "Russian":"навык"},
		{"English":"treat", "Russian":"лечить"},
		{"English":"remove", "Russian":"удалить"},
		{"English":"concern", "Russian":"забота, заботиться"},
		{"English":"university", "Russian":"университет"},
		{"English":"left", "Russian":"левый"},
		{"English":"dead", "Russian":"мертвый"},
		{"English":"discussion", "Russian":"обсуждение"},
		{"English":"specific", "Russian":"особый"},
		{"English":"box", "Russian":"ящик"},
		{"English":"outside", "Russian":"вне"},
		{"English":"total", "Russian":"всеобщий"},
		{"English":"bit", "Russian":"немного"},
		{"English":"cost", "Russian":"стоимость, стоить"},
		{"English":"girlfriend", "Russian":"подружка"},
		{"English":"market", "Russian":"рынок, купить или продать на рынке"},
		{"English":"occur", "Russian":"иметь место"},
		{"English":"research", "Russian":"исследование; исследовать"},
		{"English":"wonderful", "Russian":"чудесный"},
		{"English":"division", "Russian":"подразделение"},
		{"English":"throw", "Russian":"выбрасывать"},
		{"English":"officer", "Russian":"служащий"},
		{"English":"procedure", "Russian":"процедура"},
		{"English":"fill", "Russian":"вставлять"},
		{"English":"king", "Russian":"король"},
		{"English":"assume", "Russian":"допускать"},
		{"English":"image", "Russian":"образ"},
		{"English":"oil", "Russian":"нефть, масло"},
		{"English":"obviously", "Russian":"очевидно"},
		{"English":"unless", "Russian":"до тех пор пока не"},
		{"English":"appropriate", "Russian":"подходящий"},
		{"English":"military", "Russian":"военный"},
		{"English":"proposal", "Russian":"предложение"},
		{"English":"mention", "Russian":"упоминать"},
		{"English":"client", "Russian":"клиент"},
		{"English":"sector", "Russian":"сектор"},
		{"English":"direction", "Russian":"направление"},
		{"English":"admit", "Russian":"допускать"},
		{"English":"basic", "Russian":"основной"},
		{"English":"instance", "Russian":"пример"},
		{"English":"sign", "Russian":"знак; подписывать"},
		{"English":"original", "Russian":"оригинальный"},
		{"English":"successful", "Russian":"успешный"},
		{"English":"reflect", "Russian":"отражать"},
		{"English":"aware", "Russian":"осознавать"},
		{"English":"pardon", "Russian":"извините"},
		{"English":"measure", "Russian":"мера, измерять"},
		{"English":"attitude", "Russian":"отношение"},
		{"English":"yourself", "Russian":"(тебя) самого"},
		{"English":"exactly", "Russian":"точно"},
		{"English":"commission", "Russian":"комиссия"},
		{"English":"beyond", "Russian":"за пределами"},
		{"English":"seat", "Russian":"сидение"},
		{"English":"president", "Russian":"президент"},
		{"English":"encourage", "Russian":"воодушевлять"},
		{"English":"addition", "Russian":"дополнение"},
		{"English":"goal", "Russian":"цель"},
		{"English":"miss", "Russian":"скучать"},
		{"English":"popular", "Russian":"популярный"},
		{"English":"affair", "Russian":"дело"},
		{"English":"technique", "Russian":"техника"},
		{"English":"respect", "Russian":"уважение; уважать"},
		{"English":"drop", "Russian":"капля, капать"},
		{"English":"professional", "Russian":"профессиональный; профессионал"},
		{"English":"fly", "Russian":"летать; муха"},
		{"English":"version", "Russian":"версия"},
		{"English":"maybe", "Russian":"может быть"},
		{"English":"ability", "Russian":"способность"},
		{"English":"operate", "Russian":"действовать"},
		{"English":"goods", "Russian":"товар"},
		{"English":"campaign", "Russian":"кампания"},
		{"English":"heavy", "Russian":"тяжелый"},
		{"English":"advice", "Russian":"совет"},
		{"English":"institution", "Russian":"институт"},
		{"English":"discover", "Russian":"открывать"},
		{"English":"surface", "Russian":"поверхность"},
		{"English":"library", "Russian":"библиотека"},
		{"English":"pupil", "Russian":"ученик"},
		{"English":"refuse", "Russian":"отказывать"},
		{"English":"prevent", "Russian":"предотвращать"},
		{"English":"tasty", "Russian":"вкусный"},
		{"English":"dark", "Russian":"темный"},
		{"English":"teach", "Russian":"учить (кого-либо)"},
		{"English":"memory", "Russian":"память"},
		{"English":"culture", "Russian":"культура"},
		{"English":"blood", "Russian":"кровь"},
		{"English":"majority", "Russian":"большинство"},
		{"English":"insane", "Russian":"сумасшедший"},
		{"English":"variety", "Russian":"разнообразие"},
		{"English":"depend", "Russian":"зависеть"},
		{"English":"bill", "Russian":"банкнота"},
		{"English":"competition", "Russian":"соревнование"},
		{"English":"ready", "Russian":"готовый"},
		{"English":"access", "Russian":"доступ"},
		{"English":"hit", "Russian":"ударить, толчок; нагревать"},
		{"English":"stone", "Russian":"камень"},
		{"English":"useful", "Russian":"полезный"},
		{"English":"extent", "Russian":"расширение"},
		{"English":"employment", "Russian":"занятость"},
		{"English":"regard", "Russian":"внимание; принимать во внимание"},
		{"English":"apart", "Russian":"отдельно"},
		{"English":"besides", "Russian":"кроме того"},
		{"English":"shit", "Russian":"дерьмо"},
		{"English":"text", "Russian":"текст"},
		{"English":"parliament", "Russian":"парламент"},
		{"English":"recent", "Russian":"недавний"},
		{"English":"article", "Russian":"статья"},
		{"English":"object", "Russian":"предмет, объект"},
		{"English":"context", "Russian":"контекст"},
		{"English":"notice", "Russian":"извещение, заметить"},
		{"English":"complete", "Russian":"полный; заполнить"},
		{"English":"direct", "Russian":"прямой, управлять"},
		{"English":"immediately", "Russian":"немедленно"},
		{"English":"collection", "Russian":"коллекция"},
		{"English":"card", "Russian":"карточка"},
		{"English":"interesting", "Russian":"интересный"},
		{"English":"considerable", "Russian":"значительный"},
		{"English":"television", "Russian":"телевидение"},
		{"English":"agency", "Russian":"агентство"},
		{"English":"except", "Russian":"кроме"},
		{"English":"physical", "Russian":"физический"},
		{"English":"check", "Russian":"проверять, проверка"},
		{"English":"sun", "Russian":"солнце"},
		{"English":"possibility", "Russian":"возможность"},
		{"English":"species", "Russian":"вид"},
		{"English":"speaker", "Russian":"спикер, выступающий"},
		{"English":"second", "Russian":"секунда"},
		{"English":"laugh", "Russian":"смеяться"},
		{"English":"weight", "Russian":"вес; авторитет"},
		{"English":"responsible", "Russian":"ответственный"},
		{"English":"document", "Russian":"документ"},
		{"English":"solution", "Russian":"решение"},
		{"English":"medical", "Russian":"медицинский"},
		{"English":"hot", "Russian":"горячий, жаркий"},
		{"English":"budget", "Russian":"бюджет"},
		{"English":"river", "Russian":"река"},
		{"English":"fit", "Russian":"подходящий"},
		{"English":"push", "Russian":"толкать"},
		{"English":"tomorrow", "Russian":"завтра"},
		{"English":"requirement", "Russian":"требование"},
		{"English":"cold", "Russian":"холодный; простуда"},
		{"English":"opposition", "Russian":"оппозиция"},
		{"English":"opinion", "Russian":"мнение"},
		{"English":"drug", "Russian":"наркотик"},
		{"English":"quarter", "Russian":"четверть, квартал"},
		{"English":"option", "Russian":"опция, вариант"},
		{"English":"worth", "Russian":"стоящий"},
		{"English":"define", "Russian":"определять"},
		{"English":"influence", "Russian":"влияние, влиять"},
		{"English":"occasion", "Russian":"случай"},
		{"English":"software", "Russian":"программное обеспечение"},
		{"English":"highly", "Russian":"высоко"},
		{"English":"exchange", "Russian":"обмен"},
		{"English":"lack", "Russian":"отсутствие, недостаток; испытывать недостаток"},
		{"English":"concept", "Russian":"понятие, концепция"},
		{"English":"blue", "Russian":"синий"},
		{"English":"star", "Russian":"звезда; играть главную роль"},
		{"English":"radio", "Russian":"радио"},
		{"English":"arrangement", "Russian":"приведение в порядок"},
		{"English":"examine", "Russian":"проверять"},
		{"English":"bird", "Russian":"птица"},
		{"English":"busy", "Russian":"занятый, многолюдный"},
		{"English":"chair", "Russian":"кресло"},
		{"English":"green", "Russian":"зеленый"},
		{"English":"band", "Russian":"(музыкальная) группа"},
		{"English":"sex", "Russian":"пол"},
		{"English":"finger", "Russian":"палец"},
		{"English":"independent", "Russian":"независимый"},
		{"English":"equipment", "Russian":"оборудование"},
		{"English":"north", "Russian":"север"},
		{"English":"message", "Russian":"послание"},
		{"English":"afternoon", "Russian":"время после полудня"},
		{"English":"fear", "Russian":"страх, бояться"},
		{"English":"drink", "Russian":"пить; спиртной напиток"},
		{"English":"fully", "Russian":"полностью"},
		{"English":"race", "Russian":"раса; гонка"},
		{"English":"strategy", "Russian":"стратегия"},
		{"English":"extra", "Russian":"дополнительный"},
		{"English":"scene", "Russian":"сцена"},
		{"English":"slightly", "Russian":"слегка"},
		{"English":"kitchen", "Russian":"кухня"},
		{"English":"arise", "Russian":"подниматься"},
		{"English":"speech", "Russian":"речь"},
		{"English":"network", "Russian":"сеть"},
		{"English":"tea", "Russian":"чай"},
		{"English":"peace", "Russian":"мир"},
		{"English":"failure", "Russian":"провал"},
		{"English":"employee", "Russian":"работник"},
		{"English":"ahead", "Russian":"вперед"},
		{"English":"scale", "Russian":"шкала"},
		{"English":"attend", "Russian":"посещать"},
		{"English":"hardly", "Russian":"едва"},
		{"English":"shoulder", "Russian":"плечо"},
		{"English":"otherwise", "Russian":"по-другому"},
		{"English":"railway", "Russian":"железная дорога"},
		{"English":"supply", "Russian":"запас; снабжать"},
		{"English":"owner", "Russian":"собственник"},
		{"English":"associate", "Russian":"общаться"},
		{"English":"corner", "Russian":"угол"},
		{"English":"past", "Russian":"прошлый"},
		{"English":"match", "Russian":"матч; спичка; соответствовать"},
		{"English":"sport", "Russian":"спорт"},
		{"English":"beautiful", "Russian":"красивый"},
		{"English":"hang", "Russian":"висеть"},
		{"English":"marriage", "Russian":"свадьба"},
		{"English":"civil", "Russian":"гражданский"},
		{"English":"sentence", "Russian":"предложение"},
		{"English":"crime", "Russian":"преступление"},
		{"English":"ball", "Russian":"мяч"},
		{"English":"marry", "Russian":"жениться"},
		{"English":"wind", "Russian":"ветер"},
		{"English":"protect", "Russian":"защищать"},
		{"English":"safety", "Russian":"безопасность"},
		{"English":"partner", "Russian":"партнер"},
		{"English":"copy", "Russian":"копия, копировать"},
		{"English":"reader", "Russian":"читатель"},
		{"English":"sister", "Russian":"сестра"},
		{"English":"below", "Russian":"ниже"},
		{"English":"trial", "Russian":"судебный процесс"},
		{"English":"rock", "Russian":"скала"},
		{"English":"damage", "Russian":"вред , вредить"},
		{"English":"newspaper", "Russian":"газета"},
		{"English":"meaning", "Russian":"значение"},
		{"English":"nation", "Russian":"нация"},
		{"English":"length", "Russian":"длина"},
		{"English":"south", "Russian":"юг"},
		{"English":"branch", "Russian":"ветка"},
		{"English":"deep", "Russian":"глубокий"},
		{"English":"none", "Russian":"ни один"},
		{"English":"trust", "Russian":"доверие; доверять"},
		{"English":"pain", "Russian":"боль"},
		{"English":"positive", "Russian":"положительный"},
		{"English":"spirit", "Russian":"дух"},
		{"English":"college", "Russian":"колледж"},
		{"English":"accident", "Russian":"авария"},
		{"English":"mark", "Russian":"отметка, отмечать"},
		{"English":"works", "Russian":"завод"},
		{"English":"league", "Russian":"лига"},
		{"English":"imagine", "Russian":"представить себе"},
		{"English":"cash", "Russian":"наличные деньги"},
		{"English":"strength", "Russian":"сила"},
		{"English":"target", "Russian":"цель"},
		{"English":"travel", "Russian":"путешествие, путешествовать"},
		{"English":"pair", "Russian":"пара"},
		{"English":"gas", "Russian":"газ"},
		{"English":"male", "Russian":"мужской; существо мужского пола"},
		{"English":"contribution", "Russian":"взнос"},
		{"English":"complex", "Russian":"сложный"},
		{"English":"artist", "Russian":"художник"},
		{"English":"agent", "Russian":"агент"},
		{"English":"farm", "Russian":"ферма"},
		{"English":"glasses", "Russian":"очки"},
		{"English":"fund", "Russian":"запас, фонд"},
		{"English":"hello", "Russian":"привет"},
		{"English":"labour", "Russian":"трудовой,труд"},
		{"English":"performance", "Russian":"представление"},
		{"English":"toilet", "Russian":"туалет"},
		{"English":"presence", "Russian":"присутствие"},
		{"English":"environmental", "Russian":"относящийся к окр.среде"},
		{"English":"contact", "Russian":"контакт, контактировать"},
		{"English":"beginning", "Russian":"начало"},
		{"English":"demand", "Russian":"требовать"},
		{"English":"media", "Russian":"СМИ"},
		{"English":"employ", "Russian":"нанимать (работника)"},
		{"English":"shoot", "Russian":"стрелять"},
		{"English":"slowly", "Russian":"медленно"},
		{"English":"relatively", "Russian":"сравнительно"},
		{"English":"aid", "Russian":"помощь"},
		{"English":"speed", "Russian":"скорость"},
		{"English":"review", "Russian":"обзор"},
		{"English":"route", "Russian":"маршрут"},
		{"English":"consequence", "Russian":"последствие"},
		{"English":"telephone", "Russian":"телефон"},
		{"English":"proportion", "Russian":"пропорция"},
		{"English":"primary", "Russian":"начальный"},
		{"English":"driver", "Russian":"водитель"},
		{"English":"reform", "Russian":"реформа"},
		{"English":"annual", "Russian":"годовой"},
		{"English":"latter", "Russian":"последний (из двух)"},
		{"English":"commercial", "Russian":"коммерческий"},
		{"English":"rich", "Russian":"богатый"},
		{"English":"ring", "Russian":"звонок, звонить"},
		{"English":"distance", "Russian":"дистанция"},
		{"English":"exercise", "Russian":"упражнение, осуществлять"},
		{"English":"key", "Russian":"ключевой; ключ"},
		{"English":"skin", "Russian":"кожа"},
		{"English":"island", "Russian":"остров"},
		{"English":"separate", "Russian":"отдельный, отделять"},
		{"English":"aim", "Russian":"цель, стремиться"},
		{"English":"danger", "Russian":"опасность"},
		{"English":"credit", "Russian":"кредит"},
		{"English":"usual", "Russian":"обычный"},
		{"English":"link", "Russian":"связь, сцеплять"},
		{"English":"candidate", "Russian":"кандидат"},
		{"English":"track", "Russian":"трасса, дорожка"},
		{"English":"safe", "Russian":"безопасный"},
		{"English":"interested", "Russian":"заинтересованный"},
		{"English":"path", "Russian":"путь"},
		{"English":"plus", "Russian":"плюс"},
		{"English":"district", "Russian":"район"},
		{"English":"regular", "Russian":"регулярный"},
		{"English":"reaction", "Russian":"реакция"},
		{"English":"collect", "Russian":"собирать"},
		{"English":"debate", "Russian":"дискуссия"},
		{"English":"lay", "Russian":"класть, лежать"},
		{"English":"belief", "Russian":"вера"},
		{"English":"conclusion", "Russian":"заключение"},
		{"English":"shape", "Russian":"форма; придавать форму"},
		{"English":"vote", "Russian":"голосовать, голосование"},
		{"English":"politics", "Russian":"политика"},
		{"English":"reply", "Russian":"отвечать; ответ"},
		{"English":"press", "Russian":"нажимать"},
		{"English":"sick", "Russian":"больной"},
		{"English":"file", "Russian":"файл"},
		{"English":"western", "Russian":"западный"},
		{"English":"earth", "Russian":"земля"},
		{"English":"survive", "Russian":"выживать"},
		{"English":"boat", "Russian":"судно"},
		{"English":"prison", "Russian":"тюрьма"},
		{"English":"additional", "Russian":"дополнительный"},
		{"English":"settle", "Russian":"селиться"},
		{"English":"largely", "Russian":"обильно"},
		{"English":"observe", "Russian":"наблюдать"},
		{"English":"wine", "Russian":"вино"},
		{"English":"limit", "Russian":"ограничивать"},
		{"English":"deny", "Russian":"отрицать"},
		{"English":"straight", "Russian":"прямой"},
		{"English":"somebody", "Russian":"кто-то"},
		{"English":"writer", "Russian":"писатель"},
		{"English":"clothes", "Russian":"одежда"},
		{"English":"weekend", "Russian":"конец недели"},
		{"English":"active", "Russian":"активный"},
		{"English":"clever", "Russian":"умный"},
		{"English":"expression", "Russian":"выражение"},
		{"English":"fast", "Russian":"быстрый"},
		{"English":"nor", "Russian":"ни"},
		{"English":"video", "Russian":"видео"},
		{"English":"reality", "Russian":"реальность"},
		{"English":"hall", "Russian":"коридор"},
		{"English":"guess", "Russian":"угадать, полагать"},
		{"English":"nevertheless", "Russian":"тем не менее"},
		{"English":"perfect", "Russian":"совершенный"},
		{"English":"rain", "Russian":"дождь; идет дождь"},
		{"English":"shake", "Russian":"трясти"},
		{"English":"regional", "Russian":"региональный"},
		{"English":"vehicle", "Russian":"транспортное средство"},
		{"English":"worry", "Russian":"беспокоиться"},
		{"English":"powerful", "Russian":"мощный"},
		{"English":"possibly", "Russian":"возможно"},
		{"English":"cross", "Russian":"пересекать; крест"},
		{"English":"colleague", "Russian":"коллега"},
		{"English":"respond", "Russian":"отвечать"},
		{"English":"employer", "Russian":"работодатель"},
		{"English":"understanding", "Russian":"понимание"},
		{"English":"comment", "Russian":"комментарий, комментировать"},
		{"English":"connection", "Russian":"связь"},
		{"English":"concentrate", "Russian":"концентрироваться"},
		{"English":"ignore", "Russian":"игнорировать"},
		{"English":"phone", "Russian":"телефон; звонить по телефону"},
		{"English":"hole", "Russian":"отверстие"},
		{"English":"insurance", "Russian":"страхование"},
		{"English":"content", "Russian":"содержание"},
		{"English":"confidence", "Russian":"уверенность, доверие"},
		{"English":"alone", "Russian":"одинокий"},
		{"English":"objective", "Russian":"цель"},
		{"English":"transport", "Russian":"транспорт"},
		{"English":"flower", "Russian":"цветок"},
		{"English":"lift", "Russian":"поднимать, лифт"},
		{"English":"stick", "Russian":"палка; наклеивать, втыкать"},
		{"English":"mainly", "Russian":"главным образом"},
		{"English":"battle", "Russian":"битва"},
		{"English":"generation", "Russian":"поколение"},
		{"English":"winter", "Russian":"зима"},
		{"English":"inside", "Russian":"внутри"},
		{"English":"impossible", "Russian":"невозможный"},
		{"English":"arrange", "Russian":"подготовить, уладить"},
		{"English":"sleep", "Russian":"спать, сон"},
		{"English":"progress", "Russian":"прогресс"},
		{"English":"ship", "Russian":"корабль"},
		{"English":"volume", "Russian":"том, громкость"},
		{"English":"commitment", "Russian":"обязательство"},
		{"English":"conflict", "Russian":"конфликт"},
		{"English":"bag", "Russian":"сумка"},
		{"English":"fresh", "Russian":"свежий"},
		{"English":"fair", "Russian":"справедливый, белокурый"},
		{"English":"promise", "Russian":"обещание, обещать"},
		{"English":"introduction", "Russian":"введение"},
		{"English":"manner", "Russian":"манера"},
		{"English":"senior", "Russian":"старший"},
		{"English":"background", "Russian":"фон"},
		{"English":"touch", "Russian":"прикосновение, дотронуться"},
		{"English":"vary", "Russian":"менять"},
		{"English":"sexual", "Russian":"половой"},
		{"English":"cabinet", "Russian":"кабинет министров; шкаф"},
		{"English":"ordinary", "Russian":"обычный"},
		{"English":"painting", "Russian":"живопись"},
		{"English":"engine", "Russian":"двигатель"},
		{"English":"administration", "Russian":"администрация"},
		{"English":"tonight", "Russian":"этим вечером"},
		{"English":"adult", "Russian":"взрослый"},
		{"English":"prefer", "Russian":"предпочитать"},
		{"English":"author", "Russian":"автор"},
		{"English":"actual", "Russian":"действительный"},
		{"English":"song", "Russian":"песня"},
		{"English":"debt", "Russian":"долг"},
		{"English":"forest", "Russian":"лес"},
		{"English":"visitor", "Russian":"посетитель"},
		{"English":"repeat", "Russian":"повторить"},
		{"English":"wood", "Russian":"древесина"},
		{"English":"contrast", "Russian":"контрастность"},
		{"English":"carefully", "Russian":"аккуратно"},
		{"English":"extremely", "Russian":"чрезвычайно"},
		{"English":"wage", "Russian":"зарплата"},
		{"English":"domestic", "Russian":"домашний"},
		{"English":"threat", "Russian":"угроза"},
		{"English":"bus", "Russian":"автобус"},
		{"English":"warm", "Russian":"теплый"},
		{"English":"sir", "Russian":"сэр"},
		{"English":"range", "Russian":"ряд; располагать в порядке"},
		{"English":"replace", "Russian":"замещать"},
		{"English":"internal", "Russian":"внутренний"},
		{"English":"excellent", "Russian":"превосходный"},
		{"English":"strange", "Russian":"странный"},
		{"English":"fairly", "Russian":"справедливо"},
		{"English":"technical", "Russian":"технический"},
		{"English":"tradition", "Russian":"традиция"},
		{"English":"traffic", "Russian":"дорожное движение"},
		{"English":"until", "Russian":"до тех пор пока не"},
		{"English":"dinner", "Russian":"обед, полдник"},
		{"English":"meal", "Russian":"прием пищи"},
		{"English":"warn", "Russian":"предупреждать"},
		{"English":"award", "Russian":"награда,награждать"},
		{"English":"package", "Russian":"пакет"},
		{"English":"description", "Russian":"описание"},
		{"English":"soft", "Russian":"мягкий"},
		{"English":"stuff", "Russian":"чепуха, материал"},
		{"English":"clean", "Russian":"чистый, чистить"},
		{"English":"ticket", "Russian":"билет"},
		{"English":"umbrella", "Russian":"зонт"},
		{"English":"improvement", "Russian":"улучшение"},
		{"English":"coffee", "Russian":"кофе"},
		{"English":"appearance", "Russian":"внешность"},
		{"English":"standard", "Russian":"стандартный; стандарт"},
		{"English":"attack", "Russian":"атаковать"},
		{"English":"sheet", "Russian":"простыня, лист"},
		{"English":"category", "Russian":"категория"},
		{"English":"distribution", "Russian":"распространение"},
		{"English":"session", "Russian":"занятие"},
		{"English":"cultural", "Russian":"культурный"},
		{"English":"dodgy", "Russian":"хитрый, плутоватый"},
		{"English":"museum", "Russian":"музей"},
		{"English":"conversation", "Russian":"разговор"},
		{"English":"threaten", "Russian":"угрожать"},
		{"English":"launch", "Russian":"запускать"},
		{"English":"proper", "Russian":"настоящий, тщательный"},
		{"English":"victim", "Russian":"жертва"},
		{"English":"audience", "Russian":"аудитория"},
		{"English":"famous", "Russian":"знаменитый"},
		{"English":"master", "Russian":"мастер"},
		{"English":"lip", "Russian":"губа"},
		{"English":"religious", "Russian":"религиозный"},
		{"English":"joint", "Russian":"совместный"},
		{"English":"cry", "Russian":"плакать"},
		{"English":"potential", "Russian":"потенциальный"},
		{"English":"broad", "Russian":"ирокий"},
		{"English":"exhibition", "Russian":"выставка"},
		{"English":"judge", "Russian":"судить; судья"},
		{"English":"formal", "Russian":"формальный"},
		{"English":"housing", "Russian":"жилье"},
		{"English":"freedom", "Russian":"свобода"},
		{"English":"gentleman", "Russian":"джентльмен"},
		{"English":"attract", "Russian":"привлекать"},
		{"English":"explanation", "Russian":"объяснение"},
		{"English":"appoint", "Russian":"назначать"},
		{"English":"chief", "Russian":"шеф-повар; главный"},
		{"English":"lovely", "Russian":"прелестный"},
		{"English":"official", "Russian":"официальный"},
		{"English":"demonstrate", "Russian":"демонстрировать"},
		{"English":"construction", "Russian":"конструкция"},
		{"English":"middle", "Russian":"средний, середина"},
		{"English":"yard", "Russian":"двор"},
		{"English":"unable", "Russian":"неспособный"},
		{"English":"acquire", "Russian":"приобретать"},
		{"English":"crisis", "Russian":"кризис"},
		{"English":"surely", "Russian":"несомненно"},
		{"English":"propose", "Russian":"предлагать"},
		{"English":"west", "Russian":"запад"},
		{"English":"god", "Russian":"бог"},
		{"English":"favour", "Russian":"покровительство"},
		{"English":"equal", "Russian":"равный"},
		{"English":"flat", "Russian":"плоский; квартира"},
		{"English":"selection", "Russian":"выбор"},
		{"English":"football", "Russian":"футбол"},
		{"English":"factory", "Russian":"фабрика"},
		{"English":"circumstance", "Russian":"обстоятельство"},
		{"English":"contain", "Russian":"содержать"},
		{"English":"environment", "Russian":"окружающая среда"},
		{"English":"exam", "Russian":"экзамен"},
		{"English":"facility", "Russian":"(мн.ч.) удобства, легкость"},
		{"English":"victory", "Russian":"победа"},
		{"English":"rural", "Russian":"сельский"},
		{"English":"twice", "Russian":"дважды"},
		{"English":"sing", "Russian":"петь"},
		{"English":"deliver", "Russian":"доставлять"},
		{"English":"nobody", "Russian":"никто"},
		{"English":"invite", "Russian":"приглашать"},
		{"English":"substantial", "Russian":"существенный"},
		{"English":"egg", "Russian":"яйцо"},
		{"English":"reasonable", "Russian":"обоснованный"},
		{"English":"airplane", "Russian":"самолет"},
		{"English":"cheap", "Russian":"дешевый"},
		{"English":"mum", "Russian":"мама"},
		{"English":"quiet", "Russian":"спокойный, тихий"},
		{"English":"tend", "Russian":"склоняться к"},
		{"English":"bright", "Russian":"яркий"},
		{"English":"row", "Russian":"ряд"},
		{"English":"search", "Russian":"поиск, искать"},
		{"English":"definition", "Russian":"определение"},
		{"English":"unemployment", "Russian":"безработица"},
		{"English":"spread", "Russian":"распространять"},
		{"English":"flight", "Russian":"полет, рейс"},
		{"English":"tour", "Russian":"тур"},
		{"English":"address", "Russian":"адрес,адресовать"},
		{"English":"immediate", "Russian":"немедленный"},
		{"English":"interview", "Russian":"интервью, собеседование; проводить собеседование"},
		{"English":"everybody", "Russian":"каждый"},
		{"English":"growing", "Russian":"растущий"},
		{"English":"ought", "Russian":"должен"},
		{"English":"suitable", "Russian":"подходящий"},
		{"English":"dream", "Russian":"мечта, сон; мечтать"},
		{"English":"fruit", "Russian":"фрукт"},
		{"English":"divide", "Russian":"разделить"},
		{"English":"declare", "Russian":"декларировать"},
		{"English":"detailed", "Russian":"детальный"},
		{"English":"handle", "Russian":"рукоятка;брать руками"},
		{"English":"challenge", "Russian":"вызов, сложная задача; оспаривать"},
		{"English":"destroy", "Russian":"разрушить"},
		{"English":"mountain", "Russian":"гора"},
		{"English":"finance", "Russian":"финансы, финансировать"},
		{"English":"pension", "Russian":"пенсия"},
		{"English":"afraid", "Russian":"испуганный"},
		{"English":"murder", "Russian":"убийство"},
		{"English":"neck", "Russian":"шея"},
		{"English":"hide", "Russian":"прятать"},
		{"English":"weapon", "Russian":"оружие"},
		{"English":"offence", "Russian":"оскорбление"},
		{"English":"absent", "Russian":"отсутствующий"},
		{"English":"error", "Russian":"ошибка"},
		{"English":"representative", "Russian":"представитель"},
		{"English":"criticism", "Russian":"критика"},
		{"English":"average", "Russian":"средний"},
		{"English":"quick", "Russian":"быстрый"},
		{"English":"sufficient", "Russian":"достаточный"},
		{"English":"appointment", "Russian":"назначение"},
		{"English":"transfer", "Russian":"перемещение, перемещать"},
		{"English":"spring", "Russian":"весна"},
		{"English":"birth", "Russian":"рождение"},
		{"English":"ear", "Russian":"ухо"},
		{"English":"recognize", "Russian":"определять"},
		{"English":"recommend", "Russian":"рекомендовать"},
		{"English":"instruction", "Russian":"инструкция"},
		{"English":"democratic", "Russian":"демократичный"},
		{"English":"park", "Russian":"парк; парковать"},
		{"English":"weather", "Russian":"погода"},
		{"English":"bottle", "Russian":"бутылка"},
		{"English":"bedroom", "Russian":"спальня"},
		{"English":"kid", "Russian":"ребенок"},
		{"English":"pleasure", "Russian":"удовольствие"},
		{"English":"realize", "Russian":"представить себе"},
		{"English":"entirely", "Russian":"всецело"},
		{"English":"expensive", "Russian":"дорогой"},
		{"English":"extend", "Russian":"расширять"},
		{"English":"pick", "Russian":"срывать"},
		{"English":"protection", "Russian":"защита"},
		{"English":"select", "Russian":"выбирать"},
		{"English":"desire", "Russian":"желание"},
		{"English":"whilst", "Russian":"пока"},
		{"English":"combine", "Russian":"совмещать"},
		{"English":"temperature", "Russian":"температура"},
		{"English":"wave", "Russian":"волна"},
		{"English":"magazine", "Russian":"журнал"},
		{"English":"totally", "Russian":"абсолютно"},
		{"English":"mental", "Russian":"умственный"},
		{"English":"store", "Russian":"магазин, склад; снабжать"},
		{"English":"used", "Russian":"использованный"},
		{"English":"frequently", "Russian":"часто"},
		{"English":"scientific", "Russian":"научный"},
		{"English":"thanks", "Russian":"благодарность"},
		{"English":"beside", "Russian":"около"},
		{"English":"absolutely", "Russian":"абсолютно"},
		{"English":"settlement", "Russian":"поселение"},
		{"English":"critical", "Russian":"критичный"},
		{"English":"recognition", "Russian":"опознавание"},
		{"English":"consist", "Russian":"состоять"},
		{"English":"silence", "Russian":"молчание"},
		{"English":"dress", "Russian":"платье, одевать"},
		{"English":"dangerous", "Russian":"опасный"},
		{"English":"familiar", "Russian":"знакомый"},
		{"English":"sweet", "Russian":"сладкий, конфета"},
		{"English":"tomato", "Russian":"помидор, томатный"},
		{"English":"belong", "Russian":"принадлежать"},
		{"English":"educational", "Russian":"образовательный"},
		{"English":"sum", "Russian":"сумма"},
		{"English":"partly", "Russian":"частично"},
		{"English":"publication", "Russian":"публикация"},
		{"English":"block", "Russian":"блок, квартал; блокировать"},
		{"English":"seriously", "Russian":"серьезно"},
		{"English":"tape", "Russian":"пленка"},
		{"English":"youth", "Russian":"молодежь"},
		{"English":"elsewhere", "Russian":"где-то в другом месте"},
		{"English":"fee", "Russian":"плата, взнос"},
		{"English":"program", "Russian":"программа"},
		{"English":"treaty", "Russian":"договор"},
		{"English":"properly", "Russian":"тщательно"},
		{"English":"unlikely", "Russian":"маловероятно"},
		{"English":"guest", "Russian":"гость"},
		{"English":"code", "Russian":"код"},
		{"English":"factor", "Russian":"фактор"},
		{"English":"affect", "Russian":"наносить ущерб"},
		{"English":"hill", "Russian":"холм"},
		{"English":"household", "Russian":"(домашнее) хозяйство"},
		{"English":"screen", "Russian":"экран"},
		{"English":"sequence", "Russian":"последовательность"},
		{"English":"correct", "Russian":"правильный, исправлять"},
		{"English":"female", "Russian":"женский; существо женского пола"},
		{"English":"phase", "Russian":"фаза"},
		{"English":"daily", "Russian":"ежедневный"},
		{"English":"goat", "Russian":"козел"},
		{"English":"holiday", "Russian":"праздник"},
		{"English":"crowd", "Russian":"толпа"},
		{"English":"welcome", "Russian":"приветствовать"},
		{"English":"metal", "Russian":"металл"},
		{"English":"widely", "Russian":"широко"},
		{"English":"sky", "Russian":"небо"},
		{"English":"brain", "Russian":"мозг"},
		{"English":"expert", "Russian":"эксперт"},
		{"English":"experiment", "Russian":"эксперимент"},
		{"English":"tiny", "Russian":"крошечный"},
		{"English":"disappear", "Russian":"исчезать"},
		{"English":"photograph", "Russian":"фотография"},
		{"English":"congress", "Russian":"конгресс"},
		{"English":"reading", "Russian":"чтение"},
		{"English":"scientist", "Russian":"ученый"},
		{"English":"closely", "Russian":"близко"},
		{"English":"secure", "Russian":"охранять"},
		{"English":"thin", "Russian":"худой"},
		{"English":"plate", "Russian":"тарелка"},
		{"English":"pool", "Russian":"лужа, бассейн"},
		{"English":"emphasis", "Russian":"ударение"},
		{"English":"gold", "Russian":"золото"},
		{"English":"shout", "Russian":"кричать"},
		{"English":"location", "Russian":"расположение"},
		{"English":"display", "Russian":"показ, проявлять"},
		{"English":"heat", "Russian":"жара"},
		{"English":"gun", "Russian":"ружье"},
		{"English":"shut", "Russian":"закрыть"},
		{"English":"journey", "Russian":"путешествие"},
		{"English":"difficulty", "Russian":"трудность"},
		{"English":"growth", "Russian":"рост"},
		{"English":"violence", "Russian":"насилие"},
		{"English":"dry", "Russian":"сухой; сушить"},
		{"English":"historical", "Russian":"исторический"},
		{"English":"lunch", "Russian":"обед"},
		{"English":"noise", "Russian":"шум"},
		{"English":"bottom", "Russian":"дно"},
		{"English":"initial", "Russian":"начальный"},
		{"English":"theme", "Russian":"тема"},
		{"English":"characteristic", "Russian":"характеристика"},
		{"English":"pretty", "Russian":"хорошенький"},
		{"English":"empty", "Russian":"пустой"},
		{"English":"combination", "Russian":"сочетание"},
		{"English":"interpretation", "Russian":"перевод"},
		{"English":"escape", "Russian":"избегать"},
		{"English":"score", "Russian":"засчитывать; счет"},
		{"English":"upper", "Russian":"верхний"},
		{"English":"tooth", "Russian":"зуб"},
		{"English":"cat", "Russian":"кот"},
		{"English":"organise", "Russian":"организовывать"},
		{"English":"tool", "Russian":"инструмент"},
		{"English":"spot", "Russian":"пятно; пятнать"},
		{"English":"bridge", "Russian":"мост"},
		{"English":"double", "Russian":"двойной"},
		{"English":"conclude", "Russian":"подвести итог"},
		{"English":"relative", "Russian":"родственный"},
		{"English":"soldier", "Russian":"солдат"},
		{"English":"climb", "Russian":"взбираться"},
		{"English":"breath", "Russian":"дыхание"},
		{"English":"afford", "Russian":"позволить себе"},
		{"English":"urban", "Russian":"городской"},
		{"English":"nurse", "Russian":"няня"},
		{"English":"narrow", "Russian":"узкий"},
		{"English":"liberal", "Russian":"либеральный"},
		{"English":"coal", "Russian":"уголь"},
		{"English":"priority", "Russian":"приоритет"},
		{"English":"wild", "Russian":"дикий"},
		{"English":"membership", "Russian":"членство"},
		{"English":"approve", "Russian":"одобрять"},
		{"English":"tall", "Russian":"высокий"},
		{"English":"faith", "Russian":"вера"},
		{"English":"fix", "Russian":"фиксировать"},
		{"English":"slow", "Russian":"медленный"},
		{"English":"leading", "Russian":"ведущий"},
		{"English":"component", "Russian":"компонент"},
		{"English":"bloody", "Russian":"проклятый, кровавый"},
		{"English":"literature", "Russian":"литература"},
		{"English":"conservative", "Russian":"консервативный"},
		{"English":"variation", "Russian":"изменение"},
		{"English":"remind", "Russian":"напомнить"},
		{"English":"inform", "Russian":"информировать"},
		{"English":"neither", "Russian":"ни, также не"},
		{"English":"mass", "Russian":"масса"},
		{"English":"chemical", "Russian":"химический"},
		{"English":"careful", "Russian":"заботливый"},
		{"English":"dad", "Russian":"папа"},
		{"English":"selfish", "Russian":"эгоистичный"},
		{"English":"advantage", "Russian":"преимущество"},
		{"English":"investigate", "Russian":"исследовать"},
		{"English":"seldom", "Russian":"редко"},
		{"English":"roll", "Russian":"катить, вертеть; рулон"},
		{"English":"instrument", "Russian":"инструмент"},
		{"English":"guide", "Russian":"проводник, гид; вести"},
		{"English":"pocket", "Russian":"карман"},
		{"English":"suggestion", "Russian":"предложение, совет"},
		{"English":"tone", "Russian":"тон"},
		{"English":"attractive", "Russian":"привлекательный"},
		{"English":"dollar", "Russian":"доллар"},
		{"English":"farmer", "Russian":"фермер"},
		{"English":"funny", "Russian":"забавный"},
		{"English":"lamp", "Russian":"лампа"},
		{"English":"lucky", "Russian":"счастливый"},
		{"English":"surprise", "Russian":"сюрприз, удивление; удивлять"},
		{"English":"Christmas", "Russian":"Рождество"},
		{"English":"madam", "Russian":"мадам"},
		{"English":"pub", "Russian":"паб"},
		{"English":"illustrate", "Russian":"иллюстрировать"},
		{"English":"ride", "Russian":"ехать верхом"},
		{"English":"foundation", "Russian":"основание"},
		{"English":"restaurant", "Russian":"ресторан"},
		{"English":"alternative", "Russian":"альтернатива, альтернативный"},
		{"English":"vital", "Russian":"жизненный"},
		{"English":"burn", "Russian":"гореть, жечь"},
		{"English":"map", "Russian":"карта"},
		{"English":"device", "Russian":"устройство"},
		{"English":"customer", "Russian":"покупатель"},
		{"English":"jewellery", "Russian":"драгоценности"},
		{"English":"jump", "Russian":"прыгать"},
		{"English":"mail", "Russian":"почта"},
		{"English":"suppose", "Russian":"полагать"},
		{"English":"swim", "Russian":"плавать"},
		{"English":"unite", "Russian":"объединять"},
		{"English":"estimate", "Russian":"оценивать"},
		{"English":"conduct", "Russian":"вести"},
		{"English":"advance", "Russian":"продвижение; двигать вперед"},
		{"English":"advise", "Russian":"советовать"},
		{"English":"east", "Russian":"восток"},
		{"English":"satisfy", "Russian":"удовлетворять"},
		{"English":"hell", "Russian":"ад"},
		{"English":"effectively", "Russian":"эффективно"},
		{"English":"winner", "Russian":"победитель"},
		{"English":"mistake", "Russian":"ошибка"},
		{"English":"incident", "Russian":"происшествие"},
		{"English":"focus", "Russian":"фокус; фокусировать"},
		{"English":"representation", "Russian":"представительство"},
		{"English":"release", "Russian":"освобождение; облегчать"},
		{"English":"border", "Russian":"граница"},
		{"English":"leaf", "Russian":"лист"},
		{"English":"wash", "Russian":"мыть"},
		{"English":"observation", "Russian":"наблюдение"},
		{"English":"trip", "Russian":"поездка"},
		{"English":"gather", "Russian":"собирать"},
		{"English":"ancient", "Russian":"древний"},
		{"English":"brief", "Russian":"краткий"},
		{"English":"gate", "Russian":"ворота"},
		{"English":"elderly", "Russian":"престарелый"},
		{"English":"overall", "Russian":"всеобщий"},
		{"English":"circle", "Russian":"круг"},
		{"English":"rare", "Russian":"редкий"},
		{"English":"creation", "Russian":"создание"},
		{"English":"anybody", "Russian":"кто-нибудь"},
		{"English":"flow", "Russian":"течь; течение"},
		{"English":"external", "Russian":"внешний"},
		{"English":"capable", "Russian":"способный"},
		{"English":"recover", "Russian":"ремонтировать"},
		{"English":"shot", "Russian":"глоток спиртного; выстрел"},
		{"English":"request", "Russian":"просьба"},
		{"English":"impression", "Russian":"впечатление"},
		{"English":"neighbour", "Russian":"сосед"},
		{"English":"theatre", "Russian":"театр"},
		{"English":"hurt", "Russian":"доставлять боль"},
		{"English":"mechanism", "Russian":"механизм"},
		{"English":"atmosphere", "Russian":"атмосфера"},
		{"English":"chain", "Russian":"цепь"},
		{"English":"accompany", "Russian":"сопровождать"},
		{"English":"earn", "Russian":"зарабатывать"},
		{"English":"enemy", "Russian":"враг"},
		{"English":"desk", "Russian":"письменный стол"},
		{"English":"deputy", "Russian":"депутат"},
		{"English":"distinction", "Russian":"различие"},
		{"English":"discipline", "Russian":"дисциплина"},
		{"English":"strike", "Russian":"забастовка;ударять"},
		{"English":"married", "Russian":"женатый, замужняя"},
		{"English":"plenty", "Russian":"множество"},
		{"English":"establishment", "Russian":"учреждение"},
		{"English":"fashion", "Russian":"мода"},
		{"English":"milk", "Russian":"молоко"},
		{"English":"roof", "Russian":"крыша"},
		{"English":"secondary", "Russian":"средний"},
		{"English":"tear", "Russian":"слеза; рвать"},
		{"English":"increased", "Russian":"увеличенный"},
		{"English":"welfare", "Russian":"благосостояние"},
		{"English":"attach", "Russian":"прикреплять"},
		{"English":"typical", "Russian":"типичный"},
		{"English":"leadership", "Russian":"лидерство"},
		{"English":"negotiation", "Russian":"переговоры"},
		{"English":"count", "Russian":"считать"},
		{"English":"religion", "Russian":"религия"},
		{"English":"grey", "Russian":"серый"},
		{"English":"hence", "Russian":"отсюда"},
		{"English":"alright", "Russian":"удовлетворительно"},
		{"English":"fuel", "Russian":"топливо"},
		{"English":"mine", "Russian":"шахта, мина; мой"},
		{"English":"appeal", "Russian":"призыв; призывать"},
		{"English":"servant", "Russian":"слуга"},
		{"English":"liability", "Russian":"ответственность"},
		{"English":"conference", "Russian":"конференция"},
		{"English":"constant", "Russian":"постоянный"},
		{"English":"disease", "Russian":"болезнь"},
		{"English":"item", "Russian":"пункт"},
		{"English":"monthly", "Russian":"ежемесячный"},
		{"English":"obvious", "Russian":"очевидный"},
		{"English":"pencil", "Russian":"карандаш"},
		{"English":"per", "Russian":"за, в"},
		{"English":"profit", "Russian":"доход"},
		{"English":"remarkable", "Russian":"замечательный"},
		{"English":"hate", "Russian":"ненавидеть"},
		{"English":"shoe", "Russian":"обувь"},
		{"English":"expense", "Russian":"расход"},
		{"English":"vast", "Russian":"обширный"},
		{"English":"soil", "Russian":"почва"},
		{"English":"nose", "Russian":"нос"},
		{"English":"origin", "Russian":"происхождение"},
		{"English":"lord", "Russian":"лорд"},
		{"English":"editor", "Russian":"издатель"},
		{"English":"northern", "Russian":"северный"},
		{"English":"switch", "Russian":"включать или выключать"},
		{"English":"channel", "Russian":"канал"},
		{"English":"bone", "Russian":"кость"},
		{"English":"severe", "Russian":"свирепый"},
		{"English":"iron", "Russian":"желез; утюг"},
		{"English":"via", "Russian":"через"},
		{"English":"vision", "Russian":"проницательность, зрение"},
		{"English":"trend", "Russian":"тенденция"},
		{"English":"revolution", "Russian":"революция"},
		{"English":"terrible", "Russian":"ужасный"},
		{"English":"knee", "Russian":"колено"},
		{"English":"steal", "Russian":"украсть"},
		{"English":"unfortunately", "Russian":"к сожалению"},
		{"English":"criminal", "Russian":"преступник"},
		{"English":"signal", "Russian":"сигнал"},
		{"English":"notion", "Russian":"понятие"},
		{"English":"academic", "Russian":"академический"},
		{"English":"lawyer", "Russian":"юрист"},
		{"English":"outcome", "Russian":"последствие, выход"},
		{"English":"strongly", "Russian":"сильно"},
		{"English":"achievement", "Russian":"достижение"},
		{"English":"explore", "Russian":"исследовать"},
		{"English":"surround", "Russian":"окружать"},
		{"English":"odd", "Russian":"странный"},
		{"English":"expectation", "Russian":"ожидание"},
		{"English":"corporate", "Russian":"корпоративный, общий"},
		{"English":"prisoner", "Russian":"заключенный"},
		{"English":"rapidly", "Russian":"скоро"},
		{"English":"amongst", "Russian":"среди"},
		{"English":"afterwards", "Russian":"впоследствии"},
		{"English":"paint", "Russian":"краска; рисовать красками"},
		{"English":"citizen", "Russian":"гражданин"},
		{"English":"permanent", "Russian":"постоянный"},
		{"English":"weak", "Russian":"слабый"},
		{"English":"ourselves", "Russian":"мы (сами)"},
		{"English":"plastic", "Russian":"пластик"},
		{"English":"connect", "Russian":"соединять"},
		{"English":"height", "Russian":"высота"},
		{"English":"plane", "Russian":"самолет"},
		{"English":"lesson", "Russian":"урок"},
		{"English":"shock", "Russian":"шок; шокировать"},
		{"English":"originally", "Russian":"первоначально"},
		{"English":"knock", "Russian":"стучать"},
		{"English":"negative", "Russian":"негативный"},
		{"English":"root", "Russian":"корень"},
		{"English":"inner", "Russian":"внутренний"},
		{"English":"occupy", "Russian":"занимать"},
		{"English":"independence", "Russian":"независимость"},
		{"English":"beauty", "Russian":"красавица"},
		{"English":"struggle", "Russian":"борьба, бороться"},
		{"English":"database", "Russian":"база данных"},
		{"English":"stress", "Russian":"стресс; ставить ударение"},
		{"English":"stretch", "Russian":"растягивать"},
		{"English":"underground", "Russian":"метро"},
		{"English":"aunt", "Russian":"тетя"},
		{"English":"bicycle", "Russian":"велосипед"},
		{"English":"boyfriend", "Russian":"друг, парень"},
		{"English":"calm", "Russian":"спокойный"},
		{"English":"career", "Russian":"карьера"},
		{"English":"clearly", "Russian":"ясно"},
		{"English":"excite", "Russian":"вызывать (чувства)"},
		{"English":"lake", "Russian":"озеро"},
		{"English":"sugar", "Russian":"сахар"},
		{"English":"pen", "Russian":"ручка"},
		{"English":"trouble", "Russian":"беспокойство, беда"},
		{"English":"completely", "Russian":"полностью"},
		{"English":"existing", "Russian":"существующий"},
		{"English":"investment", "Russian":"инвестиция"},
		{"English":"normally", "Russian":"обычно"},
		{"English":"passenger", "Russian":"пассажир"},
		{"English":"relief", "Russian":"облегчение"},
		{"English":"manufacture", "Russian":"производство"},
		{"English":"snow", "Russian":"сег; идет снег"},
		{"English":"sharp", "Russian":"острый"},
		{"English":"queen", "Russian":"королева"},
		{"English":"reference", "Russian":"ссылка"},
		{"English":"virtually", "Russian":"в сущности"},
		{"English":"waste", "Russian":"растрата, трата; ненужный"},
		{"English":"contemporary", "Russian":"современный"},
		{"English":"politician", "Russian":"политик"},
		{"English":"championship", "Russian":"чемпионат"},
		{"English":"territory", "Russian":"территория"},
		{"English":"exception", "Russian":"исключение"},
		{"English":"thick", "Russian":"толстый"},
		{"English":"topic", "Russian":"тема"},
		{"English":"resident", "Russian":"постоянно проживающий"},
		{"English":"transaction", "Russian":"дело, сделка"},
		{"English":"massive", "Russian":"массивный"},
		{"English":"unique", "Russian":"уникальный"},
		{"English":"inflation", "Russian":"инфляция"},
		{"English":"assistance", "Russian":"содействие"},
		{"English":"suit", "Russian":"костюм; устраивать"},
		{"English":"parliamentary", "Russian":"парламентский"},
		{"English":"unknown", "Russian":"неизвестный"},
		{"English":"preparation", "Russian":"подготовка"},
		{"English":"badly", "Russian":"плохо"},
		{"English":"elect", "Russian":"избирать"},
		{"English":"moreover", "Russian":"более того"},
		{"English":"uncle", "Russian":"дядя"},
		{"English":"tie", "Russian":"лента; связывать"},
		{"English":"cancer", "Russian":"рак"},
		{"English":"champion", "Russian":"чемпион"},
		{"English":"breakfast", "Russian":"завтрак"},
		{"English":"licence", "Russian":"лицензия; удостоверение"},
		{"English":"minority", "Russian":"меньшинство"},
		{"English":"appreciate", "Russian":"оценивать"},
		{"English":"fan", "Russian":"болельщик"},
		{"English":"accommodation", "Russian":"помещение"},
		{"English":"democracy", "Russian":"демократия"},
		{"English":"brown", "Russian":"коричневый"},
		{"English":"taste", "Russian":"вкус"},
		{"English":"crown", "Russian":"корона"},
		{"English":"permit", "Russian":"пропуск; разрешать"},
		{"English":"buyer", "Russian":"покупатель"},
		{"English":"gift", "Russian":"подарок"},
		{"English":"angry", "Russian":"сердитый"},
		{"English":"resolution", "Russian":"разрешение; резолюция"},
		{"English":"metre", "Russian":"метр"},
		{"English":"wheel", "Russian":"колесо"},
		{"English":"tank", "Russian":"танк; бак"},
		{"English":"engage", "Russian":"привлекать"},
		{"English":"alive", "Russian":"живой"},
		{"English":"inch", "Russian":"дюйм"},
		{"English":"blame", "Russian":"осуждать"},
		{"English":"yours", "Russian":"твой"},
		{"English":"quantity", "Russian":"количество"},
		{"English":"guilty", "Russian":"виновный"},
		{"English":"coat", "Russian":"пиджак"},
		{"English":"eastern", "Russian":"восточный"},
		{"English":"involvement", "Russian":"вовлеченность; путаница"},
		{"English":"tension", "Russian":"напряжение"},
		{"English":"diet", "Russian":"диета"},
		{"English":"rarely", "Russian":"редко"},
		{"English":"prize", "Russian":"приз, награда"},
		{"English":"dominate", "Russian":"управлять"},
		{"English":"glance", "Russian":"быстрый взгляд; бросить взгляд"},
		{"English":"advertisement", "Russian":"реклама"},
		{"English":"naturally", "Russian":"естественно"},
		{"English":"relevant", "Russian":"уместный"},
		{"English":"extension", "Russian":"расширение"},
		{"English":"mix", "Russian":"смешивать"},
		{"English":"acknowledge", "Russian":"сознавать"},
		{"English":"friendly", "Russian":"доброжелательный"},
		{"English":"gain", "Russian":"извлекать выгоду"},
		{"English":"regime", "Russian":"режим"},
		{"English":"bike", "Russian":"велосипед"},
		{"English":"brush", "Russian":"щетка; чистить"},
		{"English":"confirm", "Russian":"подтверждать"},
		{"English":"curious", "Russian":"любопытный"},
		{"English":"excuse", "Russian":"просить прощения"},
		{"English":"gender", "Russian":"пол"},
		{"English":"hungry", "Russian":"голодный"},
		{"English":"kilometre", "Russian":"километр"},
		{"English":"chairman", "Russian":"председатель"},
		{"English":"fish", "Russian":"рыба"},
		{"English":"grandfather", "Russian":"дедушка"},
		{"English":"tire", "Russian":"уставать"},
		{"English":"cent", "Russian":"цент"},
		{"English":"rice", "Russian":"рис"},
		{"English":"signature", "Russian":"подпись"},
		{"English":"translate", "Russian":"переводить"},
		{"English":"useless", "Russian":"безполезный"},
		{"English":"fault", "Russian":"ошибка, просчет"},
		{"English":"ugly", "Russian":"безобразный"},
		{"English":"smart", "Russian":"живой, энергичный, интенсивный"},
		{"English":"towel", "Russian":"полотенце"},
		{"English":"grass", "Russian":"трава"},
		{"English":"basketball", "Russian":"баскетбол"},
		{"English":"quietly", "Russian":"спокойно, тихо"},
		{"English":"soap", "Russian":"мыло"},
		{"English":"complain", "Russian":"жаловаться"},
		{"English":"delivery", "Russian":"доставка"},
		{"English":"shift", "Russian":"перемещать; сдвиг"},
		{"English":"beach", "Russian":"(морской) берег"},
		{"English":"port", "Russian":"порт"},
		{"English":"depth", "Russian":"глубина"},
		{"English":"grandmother", "Russian":"бабушка"},
		{"English":"unusual", "Russian":"необычный"},
		{"English":"obligation", "Russian":"обязательство"},
		{"English":"pilot", "Russian":"пилот"},
		{"English":"yellow", "Russian":"желтый"},
		{"English":"republic", "Russian":"республика"},
		{"English":"shadow", "Russian":"тень; затенять"},
		{"English":"analyse", "Russian":"анализировать"},
		{"English":"dear", "Russian":"дорогой"},
		{"English":"anywhere", "Russian":"где-нибудь"},
		{"English":"long-term", "Russian":"долгосрочный"},
		{"English":"phrase", "Russian":"фраза"},
		{"English":"soup", "Russian":"суп"},
		{"English":"convince", "Russian":"убеждать"},
		{"English":"trick", "Russian":"обман; уловка"},
		{"English":"coast", "Russian":"берег (моря)"},
		{"English":"engineer", "Russian":"инженер"},
		{"English":"heavily", "Russian":"тяжело"},
		{"English":"glad", "Russian":"рад"},
		{"English":"charity", "Russian":"благотворительность; благотворительная организация"},
		{"English":"oppose", "Russian":"возражать"},
		{"English":"defend", "Russian":"защищать"},
		{"English":"arrest", "Russian":"арест; арестовать"},
		{"English":"warning", "Russian":"предупреждение"},
		{"English":"approval", "Russian":"одобрение"},
		{"English":"bother", "Russian":"беспокойство"},
		{"English":"novel", "Russian":"роман"},
		{"English":"currency", "Russian":"валюта"},
		{"English":"moral", "Russian":"моральный"},
		{"English":"possess", "Russian":"обладать"},
		{"English":"distinguish", "Russian":"различие"},
		{"English":"gently", "Russian":"мягко"},
		{"English":"reckon", "Russian":"считать"},
		{"English":"assist", "Russian":"содействовать"},
		{"English":"justify", "Russian":"оправдывать"},
		{"English":"behalf", "Russian":"от лица (в выражении on behalf)"},
		{"English":"setting", "Russian":"окружение; регулировка"},
		{"English":"command", "Russian":"команда"},
		{"English":"poem", "Russian":"стихотворение"},
		{"English":"stair", "Russian":"ступенька"},
		{"English":"chest", "Russian":"сундук; грудная клетка"},
		{"English":"secret", "Russian":"секрет, секретный"},
		{"English":"efficient", "Russian":"эффективный"},
		{"English":"restriction", "Russian":"ограничение"},
		{"English":"suspect", "Russian":"подозревать; подозреваемый"},
		{"English":"hat", "Russian":"шляпа"},
		{"English":"tough", "Russian":"жесткий; скандалист"},
		{"English":"healthy", "Russian":"здоровый"},
		{"English":"occasionally", "Russian":"время от времени"},
		{"English":"camp", "Russian":"лагерь"},
		{"English":"comfortable", "Russian":"комфортабельный"},
		{"English":"saving", "Russian":"спасительный"},
		{"English":"partnership", "Russian":"партнерство"},
		{"English":"wake", "Russian":"просыпаться"},
		{"English":"composer", "Russian":"композитор"},
		{"English":"provision", "Russian":"обеспечение"},
		{"English":"status", "Russian":"статус"},
		{"English":"weird", "Russian":"жуткий"},
		{"English":"abroad", "Russian":"за границей"},
		{"English":"profession", "Russian":"профессия"},
		{"English":"countryside", "Russian":"сельская местность"},
		{"English":"boot", "Russian":"ботинок"},
		{"English":"mostly", "Russian":"главным образом"},
		{"English":"sudden", "Russian":"внезапный"},
		{"English":"print", "Russian":"печатать"},
		{"English":"butter", "Russian":"масло"},
		{"English":"cinema", "Russian":"кинотеатр"},
		{"English":"data", "Russian":"данные"},
		{"English":"emerge", "Russian":"появляться"},
		{"English":"enormous", "Russian":"громадный"},
		{"English":"essential", "Russian":"необходимый"},
		{"English":"huge", "Russian":"гигантский"},
		{"English":"birthday", "Russian":"день рождения"},
		{"English":"cook", "Russian":"повар, готовить"},
		{"English":"aloud", "Russian":"вслух"},
		{"English":"amusing", "Russian":"забавный"},
		{"English":"easily", "Russian":"легко"},
		{"English":"flour", "Russian":"мука"},
		{"English":"lady", "Russian":"леди"},
		{"English":"o'clock", "Russian":"часов"},
		{"English":"thirsty", "Russian":"томимый жаждой"},
		{"English":"wisdom", "Russian":"мудрость"},
		{"English":"calculate", "Russian":"вычислять"},
		{"English":"keen", "Russian":"стремящийся (к)"},
		{"English":"autumn", "Russian":"осень"},
		{"English":"recommendation", "Russian":"рекомендация"},
		{"English":"poll", "Russian":"опрос"},
		{"English":"voluntary", "Russian":"добровольный"},
		{"English":"valuable", "Russian":"ценный"},
		{"English":"recovery", "Russian":"возврат"},
		{"English":"solve", "Russian":"решать"},
		{"English":"agriculture", "Russian":"сельское хозяйство"},
		{"English":"laptop", "Russian":"ноутбук"},
		{"English":"truth", "Russian":"правда"},
		{"English":"ice", "Russian":"лед"},
		{"English":"constitution", "Russian":"конституция"},
		{"English":"layer", "Russian":"слой"},
		{"English":"dramatic", "Russian":"драматический"},
		{"English":"golden", "Russian":"золотой"},
		{"English":"temporary", "Russian":"временный"},
		{"English":"shortly", "Russian":"коротко"},
		{"English":"initially", "Russian":"в начале"},
		{"English":"arrival", "Russian":"прибытие"},
		{"English":"protest", "Russian":"протест; возвращать"},
		{"English":"resistance", "Russian":"сопротивление"},
		{"English":"presentation", "Russian":"презентация"},
		{"English":"silent", "Russian":"молчаливый"},
		{"English":"soul", "Russian":"душа"},
		{"English":"feed", "Russian":"кормить"},
		{"English":"self", "Russian":"сам"},
		{"English":"opposite", "Russian":"напротив"},
		{"English":"pollution", "Russian":"загрязнение"},
		{"English":"wealth", "Russian":"богатство"},
		{"English":"kingdom", "Russian":"королевство"},
		{"English":"bread", "Russian":"хлеб"},
		{"English":"perspective", "Russian":"перспектива"},
		{"English":"camera", "Russian":"фотоаппарат"},
		{"English":"illness", "Russian":"болезнь"},
		{"English":"prince", "Russian":"принц"},
		{"English":"cake", "Russian":"кекс, пирожное, торт"},
		{"English":"meat", "Russian":"мясо"},
		{"English":"ideal", "Russian":"идеал"},
		{"English":"relax", "Russian":"расслаблять(ся)"},
		{"English":"purchase", "Russian":"покупать"},
		{"English":"beer", "Russian":"пиво"},
		{"English":"electricity", "Russian":"электричество"},
		{"English":"monitor", "Russian":"экран; советовать"},
		{"English":"federal", "Russian":"федеральный"},
		{"English":"captain", "Russian":"капитан"},
		{"English":"boss", "Russian":"хозяин"},
		{"English":"pour", "Russian":"наливать"},
		{"English":"creature", "Russian":"создание"},
		{"English":"urge", "Russian":"подгонять"},
		{"English":"locate", "Russian":"определять место"},
		{"English":"being", "Russian":"существо; существование"},
		{"English":"valley", "Russian":"долина"},
		{"English":"guard", "Russian":"охрана"},
		{"English":"emergency", "Russian":"непредвиденный случай"},
		{"English":"bomb", "Russian":"бомба"},
		{"English":"mood", "Russian":"настроение; наклонение"},
		{"English":"possession", "Russian":"владение"},
		{"English":"habit", "Russian":"привычка"},
		{"English":"gradually", "Russian":"постепенно"},
		{"English":"expansion", "Russian":"увеличение; экспансия"},
		{"English":"competitive", "Russian":"конкурентный"},
		{"English":"bar", "Russian":"бар; брусок"},
		{"English":"criticise", "Russian":"критиковать"},
		{"English":"potato", "Russian":"картофель"},
		{"English":"cause", "Russian":"послужить причиной"},
		{"English":"communication", "Russian":"связь"},
		{"English":"co-operation", "Russian":"кооперация"},
		{"English":"cupboard", "Russian":"шкаф для посуды"},
		{"English":"currently", "Russian":"в настоящее время"},
		{"English":"gap", "Russian":"брешь"},
		{"English":"humour", "Russian":"юмор"},
		{"English":"injury", "Russian":"травма"},
		{"English":"joy", "Russian":"радость"},
		{"English":"juice", "Russian":"сок"},
		{"English":"loss", "Russian":"потеря"},
		{"English":"nod", "Russian":"покивать"},
		{"English":"salad", "Russian":"салат"},
		{"English":"smell", "Russian":"пахнуть; запах"},
		{"English":"sofa", "Russian":"дива, софа"},
		{"English":"toy", "Russian":"игрушка"},
		{"English":"acceptable", "Russian":"допустимый"},
		{"English":"angle", "Russian":"угол"},
		{"English":"stranger", "Russian":"незнакомец"},
		{"English":"net", "Russian":"сеть, трал"},
		{"English":"sensitive", "Russian":"чувствительный"},
		{"English":"behave", "Russian":"вести себя"},
		{"English":"fellow", "Russian":"приятель"},
		{"English":"honour", "Russian":"честь"},
		{"English":"Christian", "Russian":"христианин, христианский"},
		{"English":"enable", "Russian":"давать возможность"},
		{"English":"tidy", "Russian":"приводить в порядок"},
		{"English":"kiss", "Russian":"целовать; поцелуй"},
		{"English":"preserve", "Russian":"сохранять, оберегать"},
		{"English":"personality", "Russian":"индивидуальность"},
		{"English":"wedding", "Russian":"свадьба"},
		{"English":"landscape", "Russian":"ландшафт"},
		{"English":"lock", "Russian":"замок; запирать"},
		{"English":"mirror", "Russian":"зеркало"},
		{"English":"pure", "Russian":"чистный"},
		{"English":"symptom", "Russian":"симптом"},
		{"English":"global", "Russian":"глобальный"},
		{"English":"aside", "Russian":"в сторону"},
		{"English":"tendency", "Russian":"тенденция"},
		{"English":"governor", "Russian":"правитель, губернатор"},
		{"English":"pack", "Russian":"пачка; упаковывать"},
		{"English":"bean", "Russian":"боб, фасоль"},
		{"English":"previously", "Russian":"предварительно"},
		{"English":"onion", "Russian":"лук"}
	]
}